ikawrakow/ik_llama.cpp

README.md
llama.cpp

This PR puts the `token_embedding` tensor on the GPU for the Bitnet-1.58b model. This results in a significantly improved performance on CUDA/Metal as can be seen in the table. `CUDA` is for RTX-4080, `Metal` is for a 30-code M2-Max GPU, the host CPU is a Ryzen-7950X for `CUDA`.
| model  | backend    |    test | t/s (PR)      |  t/s (main)   | Speedup |
| ------ | ---------: | ------: | ------------: | ------------: | ------: |
| IQ2_BN | CUDA       |   tg128 | 322.10 ± 0.07 | 241.34 ± 0.27 | 1.325   |   
| IQ1_BN | CUDA       |   tg128 | 301.44 ± 0.12 | 229.21 ± 0.89 | 1.315   |   
| IQ2_BN | CUDA       |   pp512 | 10780 ± 164   | 9811 ± 25     | 1.099   |   
| IQ1_BN | CUDA       |   pp512 | 10661 ± 172   | 9655 ± 21     | 1.104   |   
| IQ2_BN | Metal      |   pp512 | 723.19 ± 0.53 | …

Offload Bitnet token embeddings to the GPU

---

llama.cpp

OK, I should have checked how it was done for Gemma and do the same for Bitnet. But better late than never.

Offload Bitnet token embeddings to the GPU - the right way

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-cuda/vecdotq.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

* Same 4.5 bpw as `Q4_K`.
* Significantly reduces quantization error of LLaMA-3.1 (and also 3.0). E.g., 1.77% vs 2.9% for `Q4_K_S` for LLaMA-3.1-8B (with quantization error defined as `PPL(Q)/PPL(fp16)-1`)
* Non-linear quantization similar to `IQ4_XS` and `IQ4_NL` with the following differences
- Blocks of 16 instead of blocks of 32
- Non-linear values in each block of 16 can be on the original non-linear grid, or can be on a shifted grid. This is indicated by one bit, so we need 16 extra bits per block of 256
- So, we need `256 * 4` bits for the quants, `16 * 6` bits for the 6-bit block scales, 16 bits for the super-block float scale, and 16 bits for the shift bits, ending up with exactly 4.5 bpw
* Performance is on par with `Q4_K` on `AVX2` and `CUDA`, and slightly lower on `ARM_NEON` …

IQ4_K: SOTA 4-bit quantization

---

examples/quantize/quantize.cpp
ggml/src/ggml-quants.c
include/llama.h
src/llama.cpp

It looks like they have abandoned the Bitnet quants in PR-8151 in `llama.cpp` and are now going for quantization types in blocks of 256 similar to k- and i-quants. This of course removes support for 3B Bitnet (number of columns is not a multiple of 256) without clunky stuff such as padding, so they are going for [TriLM](https://huggingface.co/collections/SpectraSuite/trilms-unpacked-668d5f62afe0f4036925b1d2) instead, being excited about the newly added `TQ1_0` and `TQ2_0` quantizations, and `TQ2_0` being the fastest quant around on `AVX2`. So, I decided to check how it compares to the CPU implementation here.
The `IQ1_BN` and `IQ2_BN` quants in this repo rely on the tensors in the model converted to `GGUF`  being prepared as ternary, with separate tensors holding the scales. Instead of …

q2_K: allow it to detect ternary nets and quantize accordingly

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

They have abandoned the `Q1_3` and `Q2_2` quants in [PR-8151](https://github.com/ggerganov/llama.cpp/pull/8151) in `llama.cpp`, and have moved on to `TQ1_0` and `TQ2_0`. Like k-quants, these use blocks of 256 weights and utilize `Q8_K` for quantized dot products on the CPU. This removes support for [Bitnet b1.58](https://huggingface.co/1bitLLM/bitnet_b1_58-3B) (unless one adds padding to a multiple of 256), so they are now focussing on the [TriLM models](https://huggingface.co/collections/SpectraSuite/trilms-unpacked-668d5f62afe0f4036925b1d2). Unlike the previous `Q1_3` and `Q2_2`, where the quantized data only holds the ternary `-1/0/+1` values and the tensor scale is added via a separate `ggml_scale` operation, the new `TQ1_0` and `TQ2_0` include a scale in each block of 256. This …

Adding IQ2_TN for use with ternary models

---

ggml/include/ggml.h
ggml/src/ggml.c

`GGML_OP_RESHAPE, GGML_OP_VIEW, GGML_OP_PERMUTE, GGML_OP_TRANSPOSE`, along with `GGML_OP_NONE`, are all noops in `ggml`. I.e., nothing happens. But `ggml` still has a thread barrier after them, which wastes time. The waste is not too bad for large models where computations are long compared to the time taken for thread synchronization. But for small models skipping those unnecessary waits makes a noticeable difference.
Let's look at a really tiny model - the [99M parameter TriLM ternary model](https://huggingface.co/SpectraSuite/TriLM_99M_Unpacked) quantized with `IQ2_TN`.  The following table compares performance for PP-512 and TG-128 with and without the change in this PR
| CPU        | threads |          test |    t/s (main)    |  t/s (PR)        |  Speedup |
| ---------- | ------: | …

Skip barriers of noops

---

src/llama.cpp

For LLaMA-3.1 models:
* It is better to quantize all of attn_v with iq3_k instead of half of attn_v with iq4_k
* Quantizing attn_output with iq3_k results in a larger PPL decrease compared to what one expects from the added bpw.

iq2_k: slightly better bpw - accuracy compromise

---

src/llama.cpp

Use `iq5_k` for `attn_v` also when `n_gqa = 2`. 
This improves size vs quality tradeoff for Gemma-2 models.
This graph shows quantization error `PPL(Q)/PPL(f16)-1` for Gemma-2-27b-it and the various quantization types after this change. Other Gemma-2 models have similar quantization errors. The `IQ6_K` point is not visible because quantization error is zero (and the y-axis is logarithmic). Based on the peculiar legacy quants behavior, where `Q4_1` has a lower quantization error than `Q5_0`, one can hypothesize that there is a significant asymmetry in the model weights of Gemma-2-27b. This is also visible (but to a much lesser extent) for k-quants, where `Q3_K` and `Q6_K` (both of type `weight = a * q`, so assuming symmetric weights) are somewhat higher than what one would expect from …

iq4_k tweak

---

examples/llama-bench/llama-bench.cpp
ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/softcap.cu
ggml/src/ggml-cuda/softcap.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp

Some models use a so called "soft cap" in their attention portions, some may use a "soft cap" also for the final output. This is currently implemented as
```
x = ggml_scale(x, 1/softcap_parameter)
x = ggml_tanh(x)
x = ggml_scale(x, softcap_parameter)
```
By fusing these 3 operations into a single kernel, we gain about 1% on all tested backends (`AVX2, NEON, CUDA, Metal`).
Also added a SIMD-ified implementation of GeLU (`AVX512, AVX2, NEON`). This gives another ~1% performance gain on `AVX512/AVX2`. The `ggml` GeLU lookup table is faster on my M2-Max CPU, so using that on `NEON`.
The above is based on just checking the `PP-512` and `TG-128` performance. But soft cap is used in the attention portion of Gemma-2 models, so let's look at a large context where self-attention plays a more …

Fused soft cap and SIMD-ified GeLU 

---

ggml/src/ggml.c
src/llama.cpp

With this change we get 104 t/s for Gemma-2-9b with a context of 8192 tokens on a Ryzen-7950X.
For this model and context size, about 10% of the time is spent in `softcap` (5.8%) and `soft_max` (4.2%) when running on the Ryzen-7950X CPU. I wonder if it wouldn't be better to merge `softcap` and `soft_max` into a single op (for Gemma-2, `softcap` in the attention layer is immediately followed by `soft_max`)

softcap: minor improvement

---

ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/fattn-common.cuh
ggml/src/ggml-cuda/fattn-tile-f16.cu
ggml/src/ggml-cuda/fattn-tile-f32.cu
ggml/src/ggml-cuda/fattn-vec-f16.cuh
ggml/src/ggml-cuda/fattn-vec-f32.cuh
ggml/src/ggml-cuda/fattn-wmma-f16.cuh
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/softmax.cu
ggml/src/ggml-cuda/softmax.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp
tests/test-backend-ops.cpp

In a [previous PR](https://github.com/ikawrakow/ik_llama.cpp/pull/9) I has fused `scale - tanh - scale` used for "soft-capping" activations into a `GGML_OP_SOFTCAP` operation. This PR further fuses `GGML_OP_SOFTCAP` with `GGML_OP_SOFT_MAX` into a new `GGML_OP_SOFT_CAP_MAX` operation. This is useful for, e.g., self-attention in the Gemma-2 series of models, and leads to a significant performance increase.
In addition, "soft-capping" is added to flash attention. I see this has also been done in mainline `llama.cpp` in  PR-8542 and PR-9159.
Here some performance comparisons to `llama.cpp` (build 3631) for Gemma-2-2b on `CUDA` (RTX-4080), `Metal` (30-core M2-Max GPU),  `AVX2` (Ryzen-7950X) and `ARM_NEON` (M2-Max CPU). The model is quantized with `Q4_K_S` (the performance gap between this repo …

Faster Gemma2

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h

This PR adds a flash attention (FA) implementation optimized for the Zen4 architecture as part of the quest to improve CPU inference for long contexts (#25, #26).
* It is Zen4-only for now. Strictly speaking, a much smaller subset of the AVX512 specification is required in the implementation (just `AVX512F` and `AVX512DQ`) compared to what Zen4 provides, but I didn't want to have too many variants, so decided to enable for Zen4 only.
* It is not implemented for ALiBi or unmasked attention. It is trivial to add these but I didn't want to clutter the implementation with branches that are mostly irrelevant. 
The following graph compares the prompt processing (PP) performance of mainline `llama.cpp` (build: a47667cf - 3650) without (green symbols) and with (blue symbols) FA to PP performance …

Zen4 Flash Attention

---

common/common.cpp
common/common.h

The multiple choice evaluation has been broken in `llama.cpp` via commit `6ff13987a`, and this PR fixes it.
The multiple choice evaluation uses binary data stored in `params.prompt`. Commit `6ff13987a` adds prompt escape character processing, which modifies the binary data and renders unusable. To preserve whatever utility `6ff13987a` might have added, we add a flag indicating if the data stored in `params.prompt` is binary and, if so, avoid the escape processing.

Do not process prompts containing binary data for escapes

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h

This PR is a follow up on #32 and adds the ability to use quantized K- and V-cache in the flash attention (FA) kernel. `Q4_0`, `Q4_1` and `Q8_0` are supported as cache quantization types. It is trivial to add additional types, but the implementation is templated, so number of template instantiations grows quadraticly with the number of supported quantization types, so I decided to settle for these 3 types for now.
Performance is slightly lower than `fp16` cache (see graph below), so main use case is KV-cache size reduction for very large context lengths. Still, unlike mainline `llama.cpp`, performance remains strictly above no-FA.
The graph below shows PP performance as a function of context length (logarithmic scale) for Gemma-2-2b quantized with `Q4_K_S` on a Ryzen-7950X CPU.

Zen4 Flash Attnetion 2

---

ggml/src/iqk/iqk_mul_mat.cpp

If we process 2 rows in the left matrix at a time we get in the range of 20% performance boost for PP-512 (except for `Q8_0`, where performance was already higher than the other quants). The table summarizes the results or LLaMA-3.1-8B on an M2-Max CPU. As I like keeping track of how we perform relative to mainline `llama.cpp`, the table includes results for the current `llama.cpp` build (`69a480a (3660)`). tinyBLAS is enabled in `llama.cpp`, so the 33% (`Q4_0`) or 16.6% (`Q8_0`) improvement is compared to tinyBLAS, which does not provide implementation for `Q4_1`, `Q5_0` and `Q5_1` (and correspondingly the performance gap is much larger).
| Quants  |    t/s (llama.cpp)   |      t/s (main)  |       t/s (PR)   |   Speedup vs main |  Speedup vs llama.cpp |
| ------- | -------------------: | …

Performance improvements for legacy quants on ARM_NEON

---

common/common.cpp
examples/llama-bench/llama-bench.cpp
ggml/src/iqk/iqk_mul_mat.cpp

This PR adds support for using `bf16` for the kv-cache.
As Zen4 has native support for `bf16` fused-multiply-add, I was hoping that this might give better performance than `fp16`. But with this implementation it is basically the same as `fp16`. We get a tiny improvement for Gemma2-2b at 4k and 8k tokens as shown in this graph (there is no `bf16` support for kv-cache in `llama.cpp`, so no comparison in the graph).
Given this outcome, I have only enabled support for K- and V-cache both as `bf16` (i.e., one cannot mix `bf16` with other types as it is possible with `fp16`, `Q4_0`, `Q4_1` and `Q8_0`.

Zen4 Flash Attention - bf16 support

---

ggml/src/iqk/iqk_mul_mat.cpp

Only when natively supported (e.g., Zen4), else left to `ggml` to handle.
For LLaMA-3.1-8B we get `PP512 = 205` t/s vs `74 t/s` in `llama.cpp` on my Ryzen-7950X CPU.
I get `204` t/s with [llamafile](https://github.com/Mozilla-Ocho/llamafile), so I guess Justine Tunney has not contributed the more recent `tinyBLAS` improvements to `llama.cpp`.

Add support for bf16 to iqk_mul_mat

---

ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/norm.cu
ggml/src/ggml-cuda/norm.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp

Many models have one or more of `rms_norm` followed by multiplication with a normalization tensor that is (almost) always just a single row. Fusing these two operations into a single op reduces thread synchronization cost and thus has the potential to improve performance, especially for relatively small models.
This PR adds this fused operation with implementations for the CPU, CUDA and Metal. We get about 1% speedup for PP and TG for Gemma2-2b on all implemented platforms. If we look at a tiny model such as the 99M parameter ternary TriLM, performance improvement is in the range of 5-7%.

Adding fused rms_norm

---

ggml/src/iqk/iqk_mul_mat.cpp

With this change we get `PP512 = 494 t/s` (using flash attention), up from `468 t/s` (~5% improvement) running on a Ryzen-7950X CPU.
Compared to the initial `IQ2_TN` PR #13 the cumulative improvement is 15%.
Compared to `TQ2_0` in `llama.cpp`, which has now been merged, we are now 80% faster.

iq2_tn: slightly faster PP on Zen4

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

For the Bitnt-1.58b ternary models I had added `IQ1_BN` (1.625 bpw) and `IQ2_BN` (2.0 bpw) quants. But for TriLM I only added `IQ2_TN` (2.0625 bpw). This PR fills the gap adding the corresponding 1.6875 bpw quantization type `IQ1_TN`.
The matrix multiplication implementation simply reuses the existing `IQ1_BN` implementation. We just need to add the multiplication with the row scale at the end of a vector dot product between a row in the left matrix and a column in the right matrix (in `IQ1_BN` there are no scales in the quantized data, and the scale is applied separately via a `ggml_scale` operation).
While adding `IQ1_TN` to the `IQ1_BN` implementation, I noticed an optimization opportunity. As a result, this PR also improves `IQ1_BN` performance and `IQ2_BN` performance.
As …

Adding IQ1_TN - 1.6875 bpw for TriLM ternary models

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/convert.cuh
ggml/src/ggml-cuda/fattn-common.cuh
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu

Just reuse the `IQ1_BN` implementation. The only twist is that we now have the row scale stored at the beginning of the row, so we need a small modification of the dot product template to have a pointer to the beginning of the row passed to the dot product implementation.
It is slightly slower than `IQ2_TN` (305 t/s vs 320 t/s for the 4B TriLM model on RTX-4080), but this is to be expected given the bit twiddling we need to unpack the ternary bits.

Add CUDA support for IQ1_TN

---

ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal

`IQ1_BN` stores a scale at the beginning of each row, followed by `IQ1_BN` packing of the ternary quants. The existing Metal implementation does not allow for that sort of thing, so some changes were necessary (apart from adding the necessary additions in `ggml-metal.m`): 
* We modify the `kernel_mul_mm` and `kernel_mul_mm_id_impl` templates to have a dequantizer type as a template parameter (instead of a dequantization function)
* We provide a default dequantizer that does what the existing implementation does. This is used for all existing quants
* We add a dequantizer for `IQ1_BN`. It simply gets the scale from the first two bytes of a row, uses the existing `IQ1_BN` implementation to convert the ternary bits to `float4x4` or `half4x4`, and then multiplies the result with the row scale …

IQ1_TN Metal implementation

---

ggml/src/iqk/iqk_mul_mat.cpp

We don't gain as much as on a Zen4 system as there aren't as many vector registers, so we need to load/store data much more often. Still, we do get a small gain in performance.
For now it supports only `fp16` kv-cache. Quantized kv-cache will be added later.

AVX2 Flash Attention

---

ggml/src/iqk/iqk_mul_mat.cpp

This PR adds Flash Attention for `ARM_NEON`. The `Zen4/AVX2` implementation is reused with a few platform specific additions for `ARM_NEON`. As with `AVX2`, it is just for `fp16` kv-cache for now.
On `ARM_NEON` `fp16` arithmetic is used to compute `K*Q` (unlike `Zen4/AVX2`, which use `fp32`). Initially I was also using `fp16` to operate on the `K*Q` product (the `soft_max` related stuff), and that worked fine for the models I was using for testing (Gemma2-2b, TriLM-4B). But `fp16` fails for LLaMA-3.1-8B, so I had to change for `fp32`<sup>1</sup>. 
Performance gains are not as good as `Zen4/AVX2`. My guess is that due to the significantly higher memory bandwidth of the M2 Max used for testing the `ARM_NEON` implementation (compared to the `Zen4/AVX2` systems I have available), the penalty …

ARM_NEON Flash Attention

---

ggml/src/iqk/iqk_mul_mat.cpp

This PR adds two features:
* All supported CPU platforms (`Zen4, AVX2, ARM_NEON`) now have implementations for quantized kv-cache. `Q4_0, Q4_1`, and `Q8_0` can be used
* When the cache is quantized, a quantized matrix multiplication is used for `K*Q`. 
The second bullet leads to performance improvements that increase with context length. The following graph shows an example of prompt processing speed for `Q4_K_S`-quantized LLaMA-3.1-8B as a function of prompt length. The orange curve is the new implementation in this PR of cache quantized with `Q8_0`. Results are on a Ryzen-7950X CPU (`Zen4`). At 32k tokens we now have 91.4 t/s vs 64.4 t.s without FA, so a 42% improvement in the quest to [improve CPU performance for large contexts](https://github.com/ikawrakow/ik_llama.cpp/discussions/25). …

Quantized Flash Attention for all supported CPU platforms

---

src/llama.cpp

This PR changes quantization type selection for some quantization types. This leads to a lower PPL **and** a smaller quantized model size for Gemma-2 models.
The following table shows a comparison between the main branch and this PR for Gemma2-9b in terms of bits-per-weight (bpw) and quantization error (QError) defined as `PPL(Q)/PPL(fp16)-1`
| Type  |  bpw (main) | QError (main) | bpw (PR) | QError (PR) |
| ---: | ---: | ---: | ---: | ---: |
| IQ1_M | 2.20 |  78.04% | 2.15 | 67.55% |
| IQ2_XXS | 2.44 | 41.79% | 2.37 | 38.64% |
| IQ2_XS | 2.65 | 29.58% | 2.58 | 26.72% |
| IQ2_S | 2.77 | 22.12% | 2.68 | 21.82% |
| IQ2_M | 2.97 | 15.22% | 2.87 | 15.12% |
| IQ3_XXS | 3.28 | 8.46% | 3.19 | 8.07% |
| IQ3_S | 3.75 | 4.79% | 3.68 | 3.97% |
| IQ4_XS | 4.48 | 1.56% | 4.42 | 1.33% |
Basically, …

Quantization mixes tweaks

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

This PR improves `Q4_0` and `Q8_0` performance on `AVX2` and `Zen4`. The table shows comparisons to `llama.cpp` for LLaMA-3.1-8B on a Ryzen-7950X (Zen4) and a Ryzen-5975WX (AVX2) CPU.
| model         | backend    | threads |          test |     t/s (llama.cpp)  |     t/s (PR)      |   Speedup |
| --------------| ---------- | ------: | ------------: | -------------------: | ----------------: | --------: |
| llama 8B Q4_0 | Zen4       |      16 |         pp512 |        123.46 ± 0.09 |     165.26 ± 0.54 |  1.339    |   
| llama 8B Q8_0 | Zen4       |      16 |         pp512 |        141.30 ± 0.86 |     169.26 ± 0.57 |  1.200    |   
| llama 8B Q4_0 | Zen4       |       4 |         tg128 |         11.25 ± 0.02 |      13.88 ± 0.01 |  1.234    |   
| llama 8B Q8_0 | Zen4       |       4 | …

Improve Q4_0 and Q8_0 performance on AVX2/Zen4

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

The main purpose of the [previous PR](https://github.com/ikawrakow/ik_llama.cpp/pull/54) was to try to improve `K*Q` matrix multiplications for flash attention with `Q8_0` quantized k-cache. Sadly, the performance improvement that we got for `Q8_0` did not translate into better FA performance. It is a rainy Saturday, so need something to brighten my day. The last PR is very easily applied to `Q5_0`, so here we are.
The table shows performance comparison to mainline `llama.cpp` for LLaMA-3.1-8B ona Ryzen-7950X
| model         | backend    | threads |          test |     t/s (llama.cpp)  |    t/s (PR)      |  Speedup |
| --------------| ---------- | ------: | ------------: | -------------------: | ---------------: | -------: |
| llama 8B Q5_0 | CPU        |      16 |         pp512 | …

Improve Q5_0 performance on AVX2

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/convert.cuh
ggml/src/ggml-cuda/vendors/cuda.h
ggml/src/ggml-cuda/vendors/hip.h

Haha, `llama.cpp` seems to not support `bf16` on CUDA?
This PR adds it. It works fine on my `RTX-4080`, but I have no idea if it will work on older GPUs (if I understood correctly it should, with reduced performance), ROCm, etc.
Performance is the same as `f16` for TG (TG-128 = 41.2 t/s for LLaMA-3.1-8B for both).
PP is lower but quite decent for prompt processing (PP-512(`bf16`) = 5250 t/s vs PP-512(`f16`) = 7250 t/s  for LLaMA-3.1-8B). In any case, much better than running on the CPU for `bf16` models.

Adding bf16 support to CUDA

---

ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal

It is slightly slower than `fp16`, but definitely a massive improvement compared to not having `bf16` support at al. ~Didn't put any effort into optimizing the matrix x vector kernel, so it is likely one can improve `bf16` TG performance~. 
| model                          |       size |     params | backend    | ngl |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: |
| llama 8B BF16                  |  14.96 GiB |     8.03 B | Metal      | 100 |         pp512 |    538.84 ± 0.26 |
| llama 8B F16                   |  14.96 GiB |     8.03 B | Metal      | 100 |         pp512 |    587.26 ± 0.39 |
| llama 8B BF16                  |  14.96 GiB |     8.03 B | Metal      | 100 |         tg128 | …

BF16 support on Metal

---

ggml/src/CMakeLists.txt
ggml/src/ggml-common.h
ggml/src/iqk/iqk_quantize.cpp

I got tired of the "ISO C++ forbids anonymous structures" warnings that are due to the way the quants scales are defined in `ggml-common.h`, so fixing it with this PR. 
Once at it
* Also added `-Wno-c99-extensions` when building on APPLE to avoid the gazillion warnings I'm getting due to `arm_neon.h`.
* Fixed the warnings in `iqk_quantize.cpp` and added `GGML_ABORT` when an implementation is missing.

Fix compiler warnings

---

ggml/src/ggml-metal.metal

Else some models (e.g., Qwen2-7B-Instruct) produce garbage. Borrowed from PR-9595 in mainline `llama.cpp`.
Strangely enough, `K*Q` is done using `fp16` in my `ARM_NEON` FA implementation, and it works just fine there.

Use fp32 for K*Q in Metal FA implementation

---

src/llama.cpp

Phi3.5-mini uses a combined `QKV` tensor. As a result, the quantization mix strategies used for sub-3-bit quants fail. This PR fixes it, and here is what we get as quantization error using wiki text perplexity

Better sub-3-bit quantization mixes with a qkv tensor

---

ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/unary.cu
ggml/src/ggml-cuda/unary.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp

Phi-3(.5) (and also ChatGLM) uses a "SWIGLU" operation in its FFN. There is nothing special about "SWIGLU", it is just that the `ffn_up` tensor is actually a combination of the usual `ffn_up` and `ffn_gate` tensors, where in each row the first half contains the `ffn_up` weights and the second half has the `ffn_gate` weights. So that, to implement
```
silu(ffn_up * A) * (ffn_gate * A)
```
(`A` are the activations passed into the FFN network), which is common for many LLMs, one needs `swiglu(ffn_up * A) `. In a typical `ggml` style, instead of adding a dedicated op for that, `ggml` models it as 4 (!) operations
```
x1 = ggml_cont(ffn_up, first row half)
x2 = ggml_cont(ffn_up, second row half)
x3 = ggml_silu(x1)
x4 = ggml_mul(x2, x3)
```
`ggml_cont(x)` is basically a copy operation. The …

Adding SWIGLU unary op

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/rope.cu
src/llama.cpp

In this way we can avoid the Q, K, V copies being made after multiplication with the QKV tensor in, e.g., Phi-3.5-mini (see #65 for details). This results in a 6-7% speedup of PP-512(Phi-3.5-mini) on CUDA (RTX-4080). There is also a 2-3% gain on Metal (M2-Max GPU).
Here is the combined effect of this PR and PR #65 on CUDA (RTX-4080) and Metal (M2-Max 30-core GPU) for Phi-3.5-mini:
| model        | backend    | ngl | threads |          test |   t/s (llama.cpp)    |  t/s (this PR)   |  Speedup |
| -------------| ---------- | --: | ------: | ------------: | -------------------: | ---------------: | -------: |
| phi3 3B F16  | Metal      | 100 |       4 |         pp512 |       1003.22 ± 1.31 |   1063.84 ± 0.63 |  1.060   |
| phi3 3B F16  | Metal      | 100 |       4 |         tg128 | …

CUDA non-contiguous RoPE

---

src/llama-impl.h

I have been annoyed by having to wait for close to 2 seconds for the perplexity calculation to start because that's how long tokenization took when using Phi-3.5-mini (not to mention the close to 20 seconds wait when running an imatrix calculation with `wiki.train.raw`). Today my patience got exhausted and I decided to investigate. Turns out I inherited this gem when I last synced with mainline `llama.cpp` (in `src/llama-impl.h`):
```
static void replace_all(std::string & s, const std::string & search, const std::string & replace) {
if (search.empty()) {
return; // Avoid infinite loop if 'search' is an empty string
}   
size_t pos = 0;
while ((pos = s.find(search, pos)) != std::string::npos) {
s.replace(pos, search.length(), replace);
pos += replace.length();
}   
}
```
This innocently …

It is time to fix replace_all

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/cpy.cu
src/llama.cpp

On the CPU I get the exact same PPL with and without FA using `bf16` for kv-cache. But on CUDA the `bf16` kv-cache result is about the same as the `fp16` kv-cache CPU result, so I'm missing some conversion somewhere. Either way, we can now run on all platforms supported here with `bf16` kv-cache.

Allow bf16 kv-cache

---

ggml/src/iqk/iqk_mul_mat.cpp

In the llamafile repository @Djip007 has posted [PP results](https://github.com/Mozilla-Ocho/llamafile/discussions/549#discussioncomment-10780156) for short prompt lengths in steps of 1, and one sees a sharp drop in performance for 9 tokens for `Q6_K` and `Q5_K_M`. Why? For these quants llamafile uses `iqk_mul_mat` that I have contributed there, so the matrix multiplication is done using 1x8 tiles. The way it is implemented there (and also here on the main branch) is that first we multiply with 8 columns from the right matrix and then have a second pass to multiple with the remaining 9th column. This second pass is much slower, so overall performance drops. I was of course aware that there will be this effect, and always meant to investigate it, but never did. Now that we have it …

iqk_mul_mat: better srategy when nrc_y not divisible by ny

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

PP-512 performance for LLaMA-3.1-8B goes to 162.6 t/s up from 133.2 t/s (22% speedup).
This is mostly as preparation for investigating `IQ4_NL` usage for KV-cache, but still quite useful if someone is using it.

iqk_mul_mat: better iq4_nl implementation on Zen4/AVX2

---

ggml/src/iqk/iqk_mul_mat.cpp

This is a followup of PR #73 that enables usage of `IQ4_NL` for kv-cache on the CPU.

IQ4_NL kv-cache on the CPU (Zen4/AVX2/ARM_NEON)

---

ggml/src/ggml-quants.c

When I changed `iqk_mul_mat` to use type-1 dot products for type-0 legacy quants, I forgot to also change the `vec_dot_type` when the dot product is done via ggml as in flash attention. This PR fixes it.

Fix Q5_0 flash attention

---

common/common.cpp
examples/llama-bench/llama-bench.cpp
examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/cpy.cu
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-cuda/vecdotq.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml-quants.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
include/llama.h
src/llama.cpp

Main motivation was to see how it performs for quantized kv-cache. Disappointingly, it is slightly worse than `Q8_0` for K-cache and `IQ4_NL` for V-cache (this `Q8_0`+`IQ4_NL` combo needs the exact same memory as `Q6_0` for both caches).
Nevertheless, with a block size of 32 it is the same as the other legacy quants, beets `Q5_0` and `Q5_1` with a significant margin for PPL (it is almost as good as `Q6_K`), performance on Metal is quite a bit better than `Q5_0` and `Q5_1`, etc. So that, once I did the work to implement and test, why not add it?

Adding Q6_0

---

ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/unary.cu
ggml/src/ggml-cuda/unary.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp

This is useful for parallel FFNs. `unary` can be `silu, gelu` or `relu`.
Implemented for CPU, CUDA and Metal.
Speedup is disappointingly small (1-3% for PP, depending on platform and model).
Let me think some more if I want to merge it.

Fused unary(x)*y

---

ggml/include/ggml.h
ggml/src/ggml.c

It has always bugged me that `ggml` unnecessarily repeats the "quantization" of activations when the corresponding matrix multiplication cannot be done directly. E.g., `Q`, `K` and `V` all multiply the input to the self-attention layer. Similarly, `ffn_up` and `ffn_gate` multiply the same activations for parallel FFNs. "Quantization" is in quotes, because it applies to `fp16` and `bf16` tensors when the matrix multiplication function used does not work directly with `fp32` activations. There are typically 7 tensors per layer in a transformer model, so basically 3 out of 7 "quantizations" are unnecessary.
This PR remedies this unfortunate situation by storing "quantized" activations in a dedicated part of the work buffer (so the data cannot be trashed by other ops that also need a work …

Do not quantize activations if not necessary

---

ggml/src/ggml-cuda/convert.cu
ggml/src/iqk/iqk_quantize.cpp

Low-bit quants often benefit from a fudge factor applied to the (super-)block scale. When I was developing `IQ2_K` and `IQ3_K` it was faster to change the fudge factor in `ggml-cuda/convert.cu` and recompile than to change it in the quantization function and re-quantize. But when I was ready, I forgot to move the `IQ2_K` and `IQ3_K` fudge factors to quantization, so they remained in the CUDA dequantization function (and hence weren't applied anywhere else). This PR fixes this.

Cleanup scale fudge factors

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

It is similar to `IQ4_K` with the following difference
* Blocks of 32 instead of blocks of 16
* Row-wise `float` scale instead of per block instead of per super-block `ggml_half`
* 7-bit block scales instead of 6-bit - needed to ensure enough precision when using per row float scale
It ends up being 4.25 bpw, so the same as `IQ4_XS`. Why add it then? Because it has a lower quantization error than `IQ4_XS`. For some models the difference is quite significant. The following table gives some examples. Quantization error `Qerr` is defined as `PPL(Q)/PPL(f16)-1`
| Model | Qerr(IQ4_XS) | Qerr(IQ4_KS) |
| :------- | ---: | ---: |
| LLaMA-3.1-8B |  2.82% | 2.68% |
| LLaMA-3.1-8B-Instruct | 2.54% | 1.85% |
| LLaMA-3.2-3B-Instruct | 2.45% | 2.13% |
| Qwen-2.5-7B-Instruct | 2.31% | 1.62% |
| …

New SOTA quantization: 4.25 bpw IQ4_KS

---

examples/quantize-stats/quantize-stats.cpp
examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml-quants.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

It ends up being somewhere in the middle between `IQ2_XXS` and `IQ2_XS` in terms of quantized model size and quantization accuracy. This graph shows quantization error vs bpw for LLaMA-3.1-8B-Instruct
What is the point, then? Two points:
* Another proof that one can extend quantization to very low bpw **without using a codebook**. My previous attempts to do that have not been successful, so I'm quite pleased with this outcome
* Much better CPU performance compared to `IQ2_XXS` or `IQ2_XS` (or any of the i-quants that uses a codebook), see tables.
**M2-Max CPU**
| model                          |       size |     params | backend    | threads |          test |              t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | ---------------: …

IQ2_KS: 2.1875 bpw non-linear quantization

---

ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal

I completely forgot to change the `IQ2_K` Metal implementation after changing the `IQ2_K` block scales in the last PR. This PR fixes it. It also improves the performance of the `IQ2_K` Metal dot product - TG-128 for LLaMA-3.1-8B goes to 46.2 t/s up from 42.6 t./s.

Fix and optimize iq2k Metal implementation

---

ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal

I was accessing the scales as 4-byte aligned, but `IQ3_K` is not 4-byte aligned. Instead of throwing an error (as it happens
on CUDA when one makes a mistake such as this), Metal silently accepts and we get garbage. But we don't get garbage right away so one can easily notice, no we get garbage after some tokens have been generated.
PR also makes a minor optimization of the Metal dot product (~2.5% speedup).

iq3_k: fix and optimize Metal dot product

---

examples/quantize-stats/quantize-stats.cpp
examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

@Nexesenex has been asking for a 4.0 bpw quantization here and in `llama.cpp`. Well, here it is.
It uses the same non-linear grid as `IQ4_K` and `IQ4_KS`. Compared to `IQ4_KS`, we save 0.25 bpw by enforcing that the number of set bits in a group of 4 quants is even (i.e., we need 15 bits for 4 quants, so 3.75 bpw). Combined with 7+1 bits per block of 32 weights (7 bits for the scale + 1 bit indicating if there is a grid shift), we arrive at exactly 4.0 bpw. (well, there is also one float per tensor row, but that is < 0.01 bpw for 7B+ parameter models, so negligible). The best way I was able to come up with for packing the bits is to combine the 15 bits needed for the quants with the one extra bit per group of 4, needed for the block scale/grid shift, into a 16 bit unsigned integer. If …

Adding IQ4_KSS: 4.0 bpw quants

---

examples/quantize/quantize.cpp
include/llama.h
src/llama.cpp

To complement the cli based custom quantization of token_embd.weight and output.weight, the ggml_type of the following tensors can now be specified :
attn_v.weight
attn_k.weight.
attn_q_weight
attn_output.weight
attn_qkv.weight
ffn_gate
ffn_down
ffn_up

CLI - Specify GGML_TYPE to quantize for the main tensors.

---

src/llama.cpp

Pattern (attn-q -1 attn-v+1) worth to be tested on more quants levels (Q_x_K, IQx, & IQx_K) and on Llama 3.0 if confirmation is needed.
PPL 512 = -0.024 for 70b ; - 0.005 for 8b
Size = - 640MiB for 70b ; - 64MiB for 8b
70b Q5_K_S now beats Q5_K_M by -0.012 ppl, with the same source bf16 and imatrix.
I suspect that it goes similarly for L3 as well, which was quite insensitive to attn_q quantization as I discovered when I made my IQ3_L quant strategies for my own use.

Quant strategies: attn_q Q4 & attn_v Q6 for Llama 3.1 Q5_K_S

---

src/llama.cpp

Needed this to be able to run the fake models generated by the [Microsoft Bitnet implementation](https://github.com/microsoft/BitNet) to make a direct performance comparison with their Bitnet implementation (see #95).

Bitnet: make the scale tensors optional

---

ggml/include/ggml-backend.h
ggml/include/ggml.h
ggml/src/ggml-backend.c
src/llama.cpp

Introduces caching of GGML graph to avoid unnecessary full rebuild between each token. KV cache parameters, which change with each token, are updated directly in cached GGML graph. Can be disabled with GGML_DISABLE_GRAPH_CACHING environment variable.

Avoid rebuild of GGML graph for each token

---

src/llama.cpp

On CUDA GraniteMoE-1b suffers from precision issues in the attention portion, so I became curious to see why. One way to avoid the NaNs is to set the precision of the `K*Q` matrix multiplication to `F32`. What also fixes it is to apply the attention scale on `Q` before the `K*Q` multiplication (the solution I went with in this PR). One can apply the scale before or after RoPE. It works in both cases, so this really narrows it down to the `K*Q` multiplication suffering from precision issues when done in `f16`.  Strange how these models were trained in the first place.

Add support for Granite and GraniteMoE models

---

ggml/src/ggml-metal.metal

On my 30-core M2-Max TG-128 for Bitnet-1.58b-3.3B improves from 82 t/s to 94.7 t/s.
PP-512 goes from 686 t/s to 702 t/s.
Integer multiplications are expensive, so the trick used is to replace them with shifts and additions.
There is also a minor `IQ2_BN` PP-512 improvement (710 -> 714 t/s).

Faster IQ1_BN Metal implementation

---

src/llama.cpp

I had forgotten that `build_bitnet()` does not use the standerd `llm_build_ffn` function, so the fused mul-silu didn't get used automatically for Bitnet when I added it to llm_build_ffn.
This gives us another ~1% speedup for TG-128 on Metal and CUDA.

Bitnet: use the fused mul-silu in the FFN network

---

ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/unary.cu
ggml/src/ggml-cuda/unary.cuh
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml.c
src/llama.cpp

This PR
* Adds a new op `GGML_MULTI_ADD` used to sum up the contributions of the selected experts. It results in, e.g., a 7% improvement of token generation speed for Granite-1B-MoE on CUDA (RTX-4080).
* Fixes a massive inefficiency in the Metal implementation of MoE matrix multiplications (`kernel_mul_mm_id`). This leads to a nearly 6-fold prompt processing speedup for Granite-1B-MoE on Metal. But even for a much larger model such as Mixtral-8x7B the speedup is nearly a factor of 2 compared to current mainline `llama.cpp` (build: `8f275a7c (3989)`).

Faster MoE inference

---

src/llama.cpp

Use Q6_0 instead of Q5_1 for tensors incompatible with IQ5_K/Q5_K

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-quants.c
ggml/src/ggml-quants.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

In the footsteps of #118, #119, #120, #121, #122, #123, this PR adds `IQ2_BN_R4`, a 4-rows interleaved packing of the 2-bit Bitnet quantization type `IQ2_BN`.
Here is `PP-512` for Bitner-1.58b-3B on `Zen4` (Ryzen-7950X), `ARM_NEON` (M2-Max) and `AVX2` (Ryzen-5975WX)
| Platform |  Threads | IQ2_BN | IQ2_BN_R4 | Speedup |
| ---: | ---: | ---: | ---: | ---: |
| ARM_NEON |  8 |  246.57 ± 1.66 | 304.68 ± 0.77  | 1.236 |
| Zen4            | 16 | 631.27 ± 2.81  | 834.46 ± 2.77  | 1.322 |
| AVX2           | 32 | 694.17 ± 0.60  | 704.62 ± 0.60 | 1.0125 |
There aren't enough vector registers on AVX2 for all necessary accumulators when processing 8 right matrix columns at once. Hence, one needs two passes per left matrix interleaved row, so the gain on AVX2 is very minor. But on Zen4 we now achieve …

iq2_bn_r4: fastest Bitnet CPU implementation on the planet

---

ggml/src/iqk/iqk_mul_mat.cpp
src/llama.cpp

This PR accomplishes two things:
* Reduces bloat by using a template for the `ARM_NEON` matrix multiplication implementation of interleaved rows quants `Q4_0_R4, Q5_0_R4, Q6_0_R4, IQ4_NL_X4, IQ4_XS_R4, Q8_0_R4` (and I should do the same for `AVX2/Zen4`)
* Achieves a ~7% PP speedup for all `R4` quants except `IQ4_XS_R4`. With this
- `Q4_0_R4` now outperforms the hand-written assembly in mainline `llama.cpp` by a small margin (125 t/s vs 123 t/s)
- `Q8_0_R4` becomes the fastest type for prompt processing on `ARM_NEON` (PP-512 = 128 t/s for LLaMA-3.1-8B on M2-Max).
- All `R4` quants achieve PP-512 > 100 t/s for LLaMA-3.1-8B on M2-Max

R4 improvements on ARM_NEON

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

To be consistent with the other quants interleaving 4 rows.
I started the interleaved rows experiment with `IQ4_NL` and named the packing `IQ4_NL_X4`. But then I thought that `_X4` is actually ambiguous. 4 times of what? We already have quants where 4 consecutive blocks are packed together into a larger "X4" block. Because of that I named all following interleaved rows quants using "_R4" (as in 4 rows). To be consistent with this naming convention this PR renames `IQ4_NL_X4` to `IQ4_NL_R4`.

Rename iq4_nl_x4 to iq4_nl_r4

---

ggml/include/ggml.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h

We now get PP-512(LLaMA-3.1-8B) = 254 t/s on a Ryzen-7950X CPU, up from 224 t/s.

Faster IQ4_XS_R4 on Zen4

---

ggml/src/iqk/iqk_mul_mat.cpp

The implementation was using  `_mm256_maddubs_epi16`, which overflows (and gets saturated) with the unsigned version of the non-linear quants `IQ4_NL` lookup table. This PR fixes it without a noticeable performance loss.

Fix AVX2 implementation of iq4_nl_r4

---

ggml/src/iqk/iqk_mul_mat.cpp

Use integer accumulators for dot products within superblocks. I did not use this originally because according to [this Intel reference](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#ig_expand=6440,3715,4851,465,488,6424,488,4200,6554,83,4843,5760,5740,6548,6548,852,3669,6205,6205,3669,3675,5750,6375,6437,3869,2675,2675,3850,3869,2946,2946,308,1741,6044,6073,6585,7030,4851,4874,6196,6068,1741,4760,6077,4236,3667,4236,488,4044,3669,5741,6009,3869,691,5303,3843,3667,4843,110,5743,4772,1741,4046,4044,6077,4860,4860,3715,1866,1866,1866,4044,1863,1866,1866,3707,3715,5114,3667,3667,3667,5831,5738,3669,92,2692,4110,4203,4239,3869,94,853,856,1598,4953,6068,5997,4851,5997,4953,4931,6571,420,5068,488,488,4998,5010,3847,3842,4897,114,6007,4863,4761,6005,6008,3910,882,3921,60 …

Faster R4 quants on Zen4

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

This PR adds `Q8_K_R8` - 8-rows interleaved version of `Q8_K`. With that, we break the world record in prompt processing speed. Here is what we get for PP-512 with LLaMA-3.1-8B on `Zen4` (Ryzen-7950X), `AVX2` (Ryzen-5975WX) and `ARM_NEON` (M2-Max):
| Platform | PP-512 (Q8_0_R4) | PP-512 (Q8_K_R8) | Speedup |
| ARM_NEON | 128.29 ± 1.50 | 172.52 ± 4.17 | 1.345 |
| Zen4            | 268.98 ± 0.31 | 368.85 ± 0.73 | 1.371 |
| AVX2            | 234.40 ± 0.60 | 293.72 ± 0.34 | 1.253 | 
On the Ryzen-7950X, which provides native `bf16` support, this is nearly 60% faster than `bf16`. On the M2-Max, which has native `fp16` support, `Q8_K_R8` is 87% faster than `fp16`!
**Note on AVX2**: In the `AVX2` implementation one needs to use the `_mm256_madd_epi16(x, y)` …

Q8_K_R8: Fastest quantized matrix multiplications

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

Sub-4 bpw i-quants have a terrible CPU performance, so I was curious to see if we can improve by interleaving rows.
This PR adds `IQ3_XXS_R4`, a 4-row interleaved version of `IQ3_XXS`.
We get decent performance gains, but still remain much slower than k- or legacy quants. I think there is still potential for optimization, but I was getting constantly confused about shuffling signs and scales, so at the end gave up with this result. 
Here is `PP-512` for LLaMA-3.1-8B on `Zen4` (Ryzen-7950X), `ARM_NEON` (M2-Max) and `AVX2` (Ryzen-5975WX)
| Platform |  Threads | IQ3_XXS | IQ3_XXS_R4 | Speedup |
| ---: | ---: | ---: | ---: | ---: |
| ARM_NEON |  8 |  48.18 ± 0.69  | 67.45 ± 0.78 | 1.400 |
| Zen4            | 16 | 107.42 ± 0.33 | 141.62 ± 0.30   | 1.318 |
| AVX2           | 32 | 142.38 ± 0.48 …

IQ3_XXS_R4

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

Sub-4 bpw i-quants have a terrible CPU performance, so I was curious to see if we can improve by interleaving rows.
This PR adds `IQ2_XXS_R4`, a 4-row interleaved version of `IQ2_XXS`.
We get decent performance gains, but still remain much slower than k- or legacy quants. I think there is still potential for optimization, but I was getting constantly confused about shuffling signs and scales, so at the end gave up with this result. 
Here is `PP-512` for LLaMA-3.1-8B on `Zen4` (Ryzen-7950X), `ARM_NEON` (M2-Max) and `AVX2` (Ryzen-5975WX)
| Platform |  Threads | IQ2_XXS | IQ2_XXS_R4 | Speedup |
| ---: | ---: | ---: | ---: | ---: |
| ARM_NEON |  8 |  56.40 ± 0.99  | 76.34 ± 0.58 | 1.354 |
| Zen4            | 16 | 134.68 ± 0.31 | 153.60 ± 0.23   | 1.140 |
| AVX2           | 32 | 155.48 ± 0.17 …

IQ2_XXS_R4

---

ggml/src/iqk/iqk_mul_mat.cpp

Unpacking k- and i-quants is computationally expensive. Because of this, it is useful to re-use the unpacked quants for multiplication with as many columns in the right matrix as possible. At the same time one also needs to restrict the number of columns being used to some maximum number so that accumulated results can remain in vector registers, so in `iqk_mul_mat` up to 8 columns are used. But  unpacking `IQ2_XXS`, `IQ2_XS`, `IQ2_S`, `IQ3_XXS` is computationally so expensive that is cheaper to load/unload accumulated results to/from vector registers so that unpacked quants can be reused more than 8 times.
This PR adds this change using 16 columns. We get non-negligible performance gains for `IQ2_XXS`, `IQ2_XS`, `IQ2_S`, `IQ3_XXS`, and even gain somewhat for `IQ3_K`, `IQ4_K`, `IQ4_KS`, …

R4 i-quants improvements

---

ggml/src/iqk/iqk_mul_mat.cpp

It seems converting `fp16` to `fp32` is extremely slow on the Ryzen-5975WX CPU (or `ggml`'s `GGML_FP16_TO_FP32` is inadequate), so it is better to convert the `fp16` `Q8_1_x4` block scales using `AVX2` intrinsics, store the result, and then use the converted `fp32` scales when performing the dot product. This PR does that on `AVX2` for `Q4_0_R4, Q5_0_R4, Q6_0_R4` and `Q8_0_R4`.  There was no benefit on the Ryzen-7950X (`Zen4`), so not implemented there.
The table shows PP-512 comparison between the main branch and this PR for LLaMA-3.1-8B on the Ryzen-5975WX
| Quant | t/s (main) | t/s (PR) | Speedup |
| Q4_0_R4 | 251.00 ± 0.51 | 283.61 ± 0.50 | 1.130 |
| Q5_0_R4 | 236.33 ± 0.56 | 271.57 ± 0.52 | 1.149 |
| Q6_0_R4 | 231.53 ± 0.60  | 260.22 ± 0.53 | 1.124 |
| …

Faster R4 legacy quants

---

ggml/src/iqk/iqk_quantize.cpp
src/llama.cpp

Two changes:
* Add pre-tokenizer for `Falcon3` (same as `llama3`)
* Use integer arithmetic to perform the summation of a row of activations for `Q8_K16`
The second change is required for the `IQ2_BN_R4` 4-row interleaved variant. The existing implementation just sums up the `f32` values. This is fine with the original BitNet models and also with the TriLM ternary models, but with the Falcon3 ternary models I observe too large of a difference between the GPU and the CPU perplexity result. With this change the difference is greatly reduced and `IQ2_BN_R4` actually arrives at a slightly lower PPL than Microsoft's BitNet implementation (which is claimed to be "losless").

Falcon3 changes

---

ggml/include/ggml.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
src/llama.cpp

Closes #167 
I also saw requests for `Falcon3-10B-1.58b` being made in the mainline `llama.cpp` and `llamafile` repositories, so decided to add the ability to use this model with `ik_llama.cpp`.
1. Get a ternary model in Microsoft's `I2_S` format. E.g., for  ` Falcon3-10B-1.58b`
```
huggingface-cli download tiiuae/Falcon3-10B-Instruct-1.58bit-GGUF
```
2. Re-quantize to one of the ternary quantization types in this repository. E.g.,
```
./bin/llama-quantize --allow-requantize path_to_model/ggml-model-i2_s.gguf output.gguf iq2_bn
```
Works on the CPU **and** GPU (CUDA or Metal)
Enjoy!
I see perplexity is quite high (higher than the Falcon3 7B Instruct ternary model), so not sure how useful this model is in practice.

Be able to re-quantize MS BitNet I2_S models

---

examples/batched-bench/batched-bench.cpp
ggml/src/iqk/iqk_mul_mat.cpp

This PR adds two fixes:
* Make sure number of tensor rows being processed by one thread is a multiple of the number of interleaved rows when using `R4` quants also in `iqk_mul_mat_mow`
* Fix logic when we have a matrix multiplication kernel that processes 16 columns of the right matrix per kernel call (introduced on 907cde6be). The bug shows up when the number of columns in the right matrix is greater than 16 (so this kernel gets used), and the number of columns is not divisible by 16 (so there are leftover columns to be processed), so did not get caught by the usual `TG-128` and `PP-512` testing.
If quantized to `R4` quants, MoE models now work. But if run-time-repacking is used (`-rtr` command line option) to repack non-`R4` quants to `R4`, something goes wrong for MoE models that I'm …

MoE fix for R4 quants

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

This PR further improves the Flash Attention implementation as follows:
* Slightly faster `V * softmax(K * Q)` implementation. This benefits all V-cache types
* Faster implementation when the K-cache is quantized with `Q8_0` via run-time-repacking to `Q8_0_R4`.
The following graph shows prompt processing speed as a function of prompt length for LLaMA-3.1-8B quantized with `IQ4_XS` on a Ryzem-7950X CPU. The PR results are shown with black (`BF16` KV-cache) and red (`Q8_0` KV-cache) triangles, circles are used for the main branch.  I have reused the graph from the last post in #25 by just adding the results for this PR, so mainline `llama.cpp` performance is shown as well. I'm particularly pleased with the fact that `Q8_0` KV-cache is now on per or even slightly better than the natively …

More Flash Attention improvements

---

ggml/src/iqk/iqk_quantize.cpp

...when run-time-repacking is requested via `-rtr`
This massively improves performance. As this is opt-in, we do not worry about possible precision loss in the `f16 -> bf16` conversion.

On Zen4 repack fp16 models to bf16_r16

---

ggml/src/iqk/iqk_mul_mat.cpp

On the main branch `bf16` models are computed via `ggml`, which results in a horrible performance. This PR adds much better `GEMM` an `GEMV` for `bf16 x fp32`. The table shows a performance comparison between the main branch and this PR for LLaMA-3.1-8B-Instruct on a Ryzen-5975WX CPU
| model         |       size |     params | threads |      test |   t/s (main)     |  t/s (PR)     |  Speedup |
| ------------- | ---------: | ---------: | ------: | --------: | ---------------: | ------------: | -------: |
| llama 8B BF16 |  14.96 GiB |     8.03 B |      32 |     pp512 |     47.17 ± 0.04 | 152.80 ± 0.12 |  3.239   |   
| llama 8B BF16 |  14.96 GiB |     8.03 B |       1 |     tg128 |      1.37 ± 0.00 |   2.06 ± 0.00 |  1.504   |
| llama 8B BF16 |  14.96 GiB |     8.03 B |       2 |     tg128 …

Better BF16 support on AVX2

---

convert_hf_to_gguf.py
convert_hf_to_gguf_update.py
gguf-py/gguf/constants.py
gguf-py/gguf/gguf_writer.py
gguf-py/gguf/tensor_mapping.py
include/llama.h
src/llama-vocab.cpp
src/llama.cpp
src/unicode.cpp

Very direct port of https://github.com/ggerganov/llama.cpp/pull/11049.
Tested working with IQ4_K_R4 and IQ4_K. No tests so far on any quant that is supported by llama.cpp so that performance can be compared.
Tested on dual socket Xeon E5-2690 v3
Prompt processing:11.5 t/s for IQ4_K, 9.8 t/s IQ4_K_R4
Token generation: 2.75 t/s for IQ4_K, 3.10 t/s for IQ4_K_R4

Deepseek V3 support added

---

ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
src/llama.cpp

One can get better performance on `AVX2/Zen4` by interleaving 8 instead of 4 rows. I did not do it earlier because in my previous attempts performance on `ARM` suffered significantly. But in this PR I found an `ARM_NEON` implementation for 8 interleaved rows for `Q8_0` and `IQ4_XS` that is not slower or is even slightly faster than 4 interleaved rows.
Run-time-repacking from `Q8_0/IQ4_XS` will of course work, but models quantized to `Q8_0_R4` or `IQ4_XS_R4` will stop working, so putting it out there for testing and feedback.
I did not rename the types to `_R8` yet but will in case this gets merged.
Below is a graph showing prompt processing (a.k.a. prefill) performance for LLaMA-3.1-8B quantized with `IQ4_XS` on a Ryzen-7950X CPU. The cyan symbols are the results with this PR. We now get …

Interleave 8 rows (Q8_0, IQ4_XS)

---

ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
src/llama.cpp

This PR does two things
1. It changes `Q4_0_R4` to 8 interleaved rows
1. It adds the ability to apply platform specific transformations of the tensor data while repacking
Examples for the usage of 2.:
* On `ARM_NEON` it is useful to apply a `XOR` operation with a mask `0x88` to `Q4_0` quants. In this way one does not need to subtract `8` during run time. This tweak improves `Q4_0` PP performance by nearly 5% on my M2-Max CPU. This is absolutely not useful on `AVX2/Zen4`, so this becomes a platform specific transformation when run-time-repacking on an `ARM_NEON` CPU. 
* On `Zen4` one can add `128` to the signed `Q8` quants to make them unsigned (so they can be used directly in `_mmXXX_dpbusd_epi32()`. This improves `Q8_0` and `Q8_K_R8` performance by about 3%. The transformation is not …

Minor performance improvements

---

ggml/src/iqk/iqk_mul_mat.cpp
src/llama.cpp

I was playing with Deepseek-Lite and noticed that
* Quantization mixes are inadequate, so added a few quick changes to that
* As some of the tensors row sizes are not divisible by 256, we get quite a few tensors quantized with `IQ4_NL`, so I noticed that after repacking to `IQ4_NL_R4` it does not work for row sizes that are not a multiple of 128 (4 blocks). So, I fixed that (AVX2 and Zen4)
* Once at it, also fixed `Q5_0_R4` and `Q6_0_R4`
Quantization error as measured by PPL is surprisingly low for the low-bit quants, even `IQ1_S` is kind of semi-usable. It is not a "true" `IQ1_S` quantization as quite a few tensors get quantized to `IQ4_NL`, and I changed the attention tensors, which represent a tiny fraction of the overall model sizes, to be quantized with much higher bpw.  We end up …

Deepseek-Lite

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml-quants.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

Following in the foot steps of #185, this PR adds `IQ1_M_R4`, a 4-row interleaved version of `IQ1_M`. 
* I have removed the `f16` super-block scale (replaced with a `f16` per row scale) and have changed the 3-bit `IQ1_M` block scales with 4 bit. Hence, we end up using the same 1.75 bpw as `IQ1_M`.
* The above change allows to implement `IQ1_M_R4` with a block size of 32. I wanted to have this because DeepSeek-Lite, the model I'm testing with, has a lot of tensors with row sizes not divisible by 256, so a significant fraction of tensors gets quantized to `IQ4_NL` when using `IQ1_M`
*  Quantization mixes for MoE models are adjusted. Today's mainline `llama.cpp` arrives at a context-512 perplexity (`PPL(512)` in what follows) of 20.75 for DeepSeek-Lite using 2.74 bpw with `IQ1_M`. The …

IQ1_M_R4: better 1.75 bpw quants

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

to reflect the actual number of interleaved rows.

Rename q4_0_r4, q8_0_r4 and iq4_xs_r4 to _r8

---

ggml/src/ggml-cuda/norm.cu
src/llama.cpp

Derived from https://github.com/ggerganov/llama.cpp/pull/11659
Minor benefit for DeepSeek-Lite (~2% faster TG).

cuda: non-contiguous rms norm

---

ggml/include/ggml.h
ggml/src/ggml.c

While testing potential improvements of `IQ1_S_R4` quantization, I ran into NaNs while running a DeepSeek-Lite perplexity calculation. I did a `grep -r` on a folder with many big files while running the calculation and suddenly I got a NaN PPL. I repeated the calculation without doing anything else at the same time and the NaN did not happen. I then ran with 32 threads on a 16-core system and was able to reliably get a NaN at some random chunk.
This means there is a race.
The race was most likely introduced in #79 (avoid repeating already done quantizations of activations). I honestly do not understand why there could be a race, or even less do I understand why it would only happen for DeepSeek-Lite quantized with `IQ1_S_R4`. I have done countless runs since #79 and never observed …

Revert #79

---

ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h

@saood06 is still observing NaNs for DeepSeek-R1 quantized with `IQ1_S_R4`. As I don't see what else could be wrong, I'm making the following hypothesis:
1. Given the discussions about DeepSeek-R1 becoming "dumb" when `fp16` is used for some of the attention tensors, I hypothesize that there are activations that go beyond the range of `fp16` floats, which get truncated when converted from `fp32` for `fp16` for multiplications with some `fp16` model tensor.
2. If this is the case, using `Q8_1` as quantization type for activations, as `IQ1_S_R4` does, can be futile:
* Suppose there is some block of 32 activations that has a maximum $x_{\rm max} > {\rm f16}_{\rm max}$
* Suppose that the block scale $d = x_{\rm max}/127$ is in the `f16`  range. This is likely to be the case as `Q8_0` …

Use Q8_K_128 for IQ1_S_R4 and IQ1_M_R4 matrix multiplications

---

gguf-py/gguf/tensor_mapping.py
src/llama.cpp

@ikawrakow 
This PR contains the following things
- A fairydreaming commit that is supposed to increase PP
- Avoid allocating the MHA KV cache in MLA mode
- Adds a change I originally missed that is used for gguf-py.
I will follow up with:
- Having all the MoE experts load during warmup, that can be placed in this PR if you want, or a separate one. It is a very large QoL feature for large MoE. Without it the model is slowly loaded in on use, with it, the model is loaded immediately and at a faster rate.
- The mmap based KV cache buffer, it is functional but I have yet to make it a CLI option.

 Deepseek MLA Optimizations V2

---

common/common.cpp
common/common.h
convert_hf_to_gguf.py
examples/llama-bench/llama-bench.cpp
ggml/src/ggml.c
gguf-py/gguf/constants.py
gguf-py/gguf/tensor_mapping.py
include/llama.h
src/llama.cpp

This PR is derived from #180. The difference to #180 is that MLA is made optional. It is off by default, and can be turned on using the added `-mla` or `--use-mla` command line option.
Rationale: MLA improves TG speed, especially when there is a long context. But it also makes prompt processing significantly slower. Hence, MLA is made optional since advantage/disadvantage is use case dependent.
Being able to select or deselect MLA at run time is possible due to the fact that #180 leaves the original `wkv_b` tensor and its decomposition into `wk_b` and `wv_b` in the model. This is somewhat wasteful, but these tensors are not very large and now come handy to easily select between the two attention implementations. 
In addition:
* It is now possible to use a model converted without this PR …

Add optional MLA

---

common/common.cpp
examples/llama-bench/llama-bench.cpp
src/llama.cpp

First commit is a port of: https://github.com/ggerganov/llama.cpp/pull/11571
The second commit is based on what fairydreaming has reported here https://github.com/ggerganov/llama.cpp/discussions/11733 and also unify's warmup to always be one token.
This allows warmup to actually warmup an MoE model as all experts are exercised.

 Load all MoE experts during warmup and make warmup 1 token

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h
src/llama.cpp

This PR adds FA support for models where K and V head sizes are different, such as DeepSeek-R1 and DeepSeek-Lite. It only works with the standard attention mechanism, I have yet to look into FA with MLA.
We get a nice speedup for PP, increasing with context length, but TG is not faster. I want to play some more with it, but throwing it out there if someone wants to try. For sure this allows longer contexts to be processed as `-ctk q8_0 -ctv q8_0` seems perfectly adequate.

DeepSeek FA support (CPU only)

---

examples/imatrix/imatrix.cpp

I hear reports that people are having trouble creating imatrix data for models with many experts (e.g., DeepSeek-R1, Arctic). For such models it may be very hard to activate all experts in all layers, which it turns out leads to the data for **the entire** tensor containing experts with missing data to be not stored in the imatrix file. Which then prevents usage of the imatrix data for low-bit quantization of such models.
It wasn't like this when I added the imatrix to `llama.cpp`, but it turns out the protection police has been at work and has added these checks, which I then inherited when syncing with upstream. Thanks to @saood06 for making me aware of this unfortunate situation.
This PR reduces the powers of the protection police. If a tensor is found that has partial contributions to …

Fix imatrix overprotectiveness

---

src/llama.cpp

After PR #205 we have two KV caches left when using MLA:
* `kv_l` - contiguous, not transposed
* `kvt_l` - a transposed version of `kv_l`
`kv_l` can be quantized, and this PR adds the necessary changes.
`kvl_t`, being a transposed version of `kv_l`, cannot be quantized. It can be eliminated by setting `MLA_USE_TRANSPOSED_CACHE` to 0 in `llama.cpp` (but then `kv_l` cannot be quantized as making a contiguous transposed tensor out of a quantized tensor as needed during inference does not work at this point).
Apart from reducing required KV cache memory, a quantized `kv_l` cache can also slightly improve TG performance after a long prompt. Here is a comparison between the main branch and this PR for `tg64@ppN` for different prompt lengths `N`. Model is `IQ4_XS` quantized DeepSeek-Lite. The …

MLA: allow Q8_0 K-cache for MLA

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h

This PR
* Absorbs the `iqk` matrix multiplication logic in `ggml` into a new `iqk` function `iqk_mul_mat_4d`. The change to `ggml` to incorporate the `iqk`-added functionality is now much less intusive
* Adds to `iqk_mul_mat_4d` special handling of the TG case with GQA. In this case the `K` and `V` tensors have a shape `N x M x Lkv` (`N` is the head size, `Lkv` is the number of KV heads), and they multiply a tensor (`Q` or `K*Q`) with shape `N x 1 x L` (`L` is the number of heads, `L > Lkv`). If we rearrange `Q` as `N x L/Lkv x Lkv`, we now have GEMM instead of GEMV, and this is significantly faster.
This better approach only gives noticeable TG speedup for long context (large KV cache), as without that the fraction of time spent on the `K*Q` and `V*softmax(K*Q)` is small. So, here is a …

Faster CPU TG for GQA models

---

ggml/src/iqk/iqk_quantize.cpp

When I implemented run time repacking, I required the tensor to be 2D to be eligible for repacking, I guess to simplify the code. But I forgot about MoE models, where expert weights are in 3D tensors.
This PR fixes that. This leads to very significant performance gains. E.g., for DeepSeek-Lite quantized with `IQ4_XS`, we get `PP-512 = 545` t/s on the main branch, and `PP-512 = 677 t/s` with this PR when using run time repacking.

Repack also experts

---

common/common.cpp
examples/llama-bench/llama-bench.cpp
examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

What is `Q8_KV`? It is 8-bit quantization with a single scale per tensor row (so, no blocks at all). That may not be accurate enough for model quantization, but using it for KV cache quantization seems plausible, considering that there rows are defined by the head size, so contain 64, 80, 96, 128, 192, or 256 elements for all LLMs currently in circulation. We are not looking for KV cache size reduction but rather for improving inference performance for long contexts. This is especially relevant for MLA (DeepSeek) as in FA the kernels are highly optimized, so large improvements may not be really possible.
Caveat: everything is CPU only, there is no CUDA or Metal implementation.
The following changes are made:
* New types `Q8_KV` and `Q8_KV_R8` are added. `Q8_KV_R8` is `Q8_KV` with 8 …

Q8_KV: 8-bit quantization type targeting the KV cache

---

ggml/src/iqk/iqk_mul_mat.cpp

Apparently there are many people who would prefer to just run Unsloth's `IQ1_S` DeepSeek-R1 model as is instead of quantizing to `IQ1_S_R4` and taking advantage of the better model quality and improved inference speed.
So, here is a `iqk_mul_mat.cpp` implementation for `IQ1_S`.
I don't have the ability to run DeepSeek-R1, so using DeepSeek-Lite as a surrogate to test performance as it has the same architecture. The downside is that we don't test "pure" `IQ1_S` performance as various tensors that would have been quantized to `IQ1_S` get quantized to `IQ4_NL` due to their row sizes not being divisible by 256 (the `IQ1_S` block size). Performance tests are run on Ryzen-7950X (`Zen4`), Ryzen-5975WX (`AVX2`) and M2-Max CPU (`NEON`)
| model               | backend    | threads |     test | …

Optimized GEMM/GEMV for IQ1_S

---

ggml/src/iqk/iqk_mul_mat.cpp

I have broken it quite a while ago when I changed the NEON implementation to do two rows at a time. I haven't noticed as all models I typically use have row sizes that are multiple of 128. But as I was working on the `IQ1_S` NEON implementation for PR #212, I was testing with DeepSeek-Lite (where K cache row size is 576, so not divisible by 128), using `Q8_0` for K cache (but no FA, where it works), and was getting NaNs or gibberish. I lost so much time until I finally realized that the issue is with the K cache `Q8_0` matrix multiplication rather than my `IQ1_S` implementation.
This PR fixes this.

Fix NEON gemm/gemv for legacy quants when row size is not divisible by 128

---

ggml/src/iqk/iqk_mul_mat.cpp

The `K*Q` and `V*softmax(K*Q)` matrix multiplications have the shape
$$\left(K x N_t x N_k\right) \times \left(K x N_b x N_h\right)$$ 
where $K$ is the head size, $N_t$ is the number of tokens in the cache, $N_b$ is the number of tokens in the current batch, $N_k$ is the `K` or `V` number of heads, and $N_h$ is the total number of heads. In `llama.cpp` this tensor multiplication has been traditionally performed as $N_h$ consecutive matrix multiplications, each being of shape
$$\left(K x N_t\right) \times \left(K x N_b\right)$$
The issue with this is that for token generation (TG) we have $N_b = 1$, so we are dealing with $N_h$ matrix-vector multiplications, which are notoriously memory bound, and hence limit performance for large cache size (long contexts). To add insult to injury, the …

Better strategy for attention matrix multiplications when generating tokens 

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

No new op, instead the fusing is done during graph compute in the CPU back end (same could be also done for the other back ends).
The advantage of fusing the `ffn_up` and `ffn_gate` matrix multiplication is that a) there is one less thread synchronization; b) half the threads evaluate `ffn_up` and the other half `ffn_gata` in parallel.
This leads to a small but measurable performance gain (1-2%) for PP and TG.
As for MoE models the `ffn_up` and `ffn_gate` matrix multiplications are always followed by element wise  multiplication of `result1 * op(result2)` (where `op` is `SILU` or `GELU`), one could go one step further and add a new operation that does all of this together. This would a) further reduce thread synchronization cost and b) reduce memory writes/loads by removing the need for …

Fuse MoE up and gate matrix multiplications

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/unary.cu
ggml/src/ggml-cuda/unary.cuh
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h
include/llama.h
src/llama.cpp

In all MoE models one has the following sequence of operations as part of the feed forward network (simplified):
```
up   = ggml_mul_mat_id(up_exps, cur, selected_experts)
gate = ggml_mul_mat_id(gate_exps, cur, selected_experts)
act  = ggml_silu(gate) or ggml_gelu(gate)
par  = ggml_mul(up, act)
down = ggml_mul_mat_id(down_exps, par)
```
Each of the `ggml_mul_mat_id` operations requires a search of activated experts (which is the same for all 3). Also, `up` and `gate` have the same second operand so that, if they are quantized, the quantization is unnecessarily repeated. There is a barrier after each operation. On CUDA there is no implementation of indirect matrix multiplication, so each `ggml_mul_mat_id` op triggers a copy of the rows of the second operand to a contiguous memory block, …

Fused MoE ffn_up and ffn_gate

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/src/ggml-alloc.c
ggml/src/ggml-backend.c
ggml/src/ggml-cuda.cu
ggml/src/ggml.c
include/llama.h
src/llama.cpp

It seems this PR amounts to most of the "secret sauce" of KTransformers. 
We add a command line option to override where model weights are stored using regular expressions. This allows to keep the MoE experts on the CPU and to offload only the attention and not repeating layers to the GPU. The PR is inspired by https://github.com/ggml-org/llama.cpp/pull/11397, but `ik_llama.cpp` has now diverged so much from mainline that I had to do most of it new.
Unfortunately I cannot test with DeepSeekV3/R1, but here is what I get for DeepSeek-Lite (very similar MoE architecture) using
```
./bin/llama-bench -m deepseek_lite.gguf -p 512 -n 128 -t 16 -ngl 100 -rtr 1 -ot "\.ffn_.*_exps\.=CPU"
```
| model                          |       size |  threads |     test |  t/s (CPU only)  | t/s (CPU+GPU)    | …

Give the user the option to override where model weights are stored

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/src/ggml-cuda/mmvq.cu
include/llama.h
src/llama.cpp

The `-mla` (or `--mla-use`) command line option turns from previously a boolean value to an integer:
* `mla = 0`: use standard attention
* `mla = 1`: use MLA with transposed cache - this is the existing MLA implementation
* `mla = 2`: use MLA without transposed cache - this is the option added by this PR
Why do we need this? Apparently many people are interested in using the maximum context length of long context models. For DeepSeekV3/R1, the rage of the day, it is 163k tokens. This requires a lot of RAM/VRAM. Let's take a look:
* **Standard attention (mla = 0):** memory required per token is `n_layer * (3072 * sizeof(K cache element) + 2048 * sizeof(V cache element))`. For DeepSeekV3/R1 this works out to **610 kB** per token when using `fp16` cache. For `Q8_0` K and V cache it is **324 …

Option to use MLA without a transposed cache

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/src/ggml-cuda/concat.cu
ggml/src/ggml.c
include/llama.h
src/llama.cpp

I have been focusing on reducing the KV cache size, but as per the lengthy exchange in #235 the actual issue for using a very long context is the size of the compute buffers. E.g., if one attempted to run DeepSeekV3/R1 with the claimed 163k tokens maximum context length, one would need over 40 GB of CUDA compute buffer **per GPU**. But even if running on the CPU, 40 GB is nothing to sneeze at.
This PR solves the problem. For GPU and CPU inference.
Where is the issue? The `K*Q` tensor, computed in the attention portion of the network, is of size `n_ctx x n_ubatch x n_head x sizeof(float)`. One also needs `softmax(K*Q)` (of the same size), but the back-end is fortunately clever enough to reuse the same buffer. DeepSeekV3/R1 has `n_head = 128`, so with the default u-batch size of 512 tokens, …

Reduce size of compute buffers

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/argsort.cu
ggml/src/ggml-cuda/argsort.cuh
ggml/src/ggml-cuda/getrows.cu
ggml/src/ggml.c
include/llama.h
src/llama.cpp

The idea behind this PR is very simple: we define new parameters (specified via the command line) $K_{\rm min}$ and $t$. During inference experts are normally selected by sorting their computed probabilities $p_i$ in descending order and picking the top $K$ experts. We modify this expert selection algorithm by always selecting the top $K_{\rm min}$ experts ($K_{\rm min} < K$), and using experts between $K_{\rm min}$ and $K$ only if $p_i > t\cdot p_0$ (i.e., only if their probability $p_i$ relative to the top expert probability $p_0$ is greater than the specified threshold $t$). If we set $t = 0$, this expert selection modification is never invoked, so we have the behavior of the original model. If we set $t = 1$, we use a fixed number of experts $K_{\rm min}$ (the same can be achieved by …

SER - Smart Expert Reduction

---

ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
src/llama.cpp

This PR adds Flash Attention for MLA for the CPU back-end. This should be of interest to people running DeepSeeklV3/R1 on the CPU.
Benefits:
* Reduced KV cache size - only the K-cache is required. Hence, the KV cache can be quantized. One can achieve the same with `-mla 2`, but this comes at a significant performance penalty (the transposed view of the cache needs to be computed on each compute graph evaluation)
* Reduced compute buffer size - the `K*Q` tensor, which is the major contributor to compute buffer size for long contexts, never materializes. One can keep the compute buffer size to a desired maximum size using the `-amb` option, but this comes with the inconvenience of having to think about compute buffer sizes, and a small performance penalty for large contexts
* Same or …

Flash MLA (CPU only)

---

examples/quantize/quantize.cpp
include/llama.h
src/llama.cpp

For DeepSeekV3/R1 it is handy to be able to define custom rules for picking quantization types for the various tensors. Well, this is useful in general, but particularly useful for very large models where one wants to squeeze the last bit of quantized model quality for the smallest possible model size.
This PR adds this ability. Using
```
./bin/llama-quantize --imatrix some_imatrix --custom-q "regex1=typ1,regex2=type2..." some_model some_output_file some_base_quant
```
one can pass custom rules to the quantization function. The rules are comma separated (but one can also use multiple `--custom-q` arguments). The custom rules are processed in order and the first match is taken. So, for instance, if I use
```
--custom-q "\.ffn_down_exps\.weight=iq4_nl,\.ffn_.*_exps\.weight=iq1_s_r4"
```
the …

Custom quantization rules with regular expressions

---

ggml/src/ggml.c
src/llama.cpp

MLA as used in the DeepSeek models is great for token generation (TG), but prompt processing (PP) speed is much lower compared to standard attention even with FA enabled.
This PR improves FlashMLA speed by a large margin. FlashMLA is CPU only, but the PR paves the way to perhaps also get it on CUDA (but this is left for a future PR).
The following table compares FlashMLA PP speed for DeepSeek-Lite quantized as `IQ4_NL` between the main branch and this PR. CPU is Ryzen-7950X, the cache is quantized with `Q8_0`, `fmoe` is on.
| model                |          test |     t/s (main)   |   t/s (PR)       |  Speedup |
| ---------------------| ------------: | ---------------: | ---------------: | -------: |
| deepseek2 16B IQ4_NL |         pp512 |    605.29 ± 4.92 |    681.72 ± 1.12 |  1.126   | …

Faster FlashMLA prompt processing

---

src/llama.cpp

This PR adds FlasMLA on CUDA. It is enabled via `-mla 2 -fa`.
I observe a very strange slow down for TG that is caused by a very slow `ffn_gate_exps` matrix multiplication. As I was not able to resolve what causes this, for now TG will got via the regular `mla = 2` route, so TG performance remains the same as we had with `mla = 2, fa = 0`.
Prompt processing speed is massively improved for long contexts, and is almost on par with standard FA. The following table shows a comparison between `mla = 2` without FA and FlashMLA. Model is `IQ4_NL` quantized DeepSeek-Lite, GPU is RTX-4080. `fmoe` is on, `u_batch = 2048`
| model                | mla | fmoe |          test |    t/s (no FA)   |   t/s (FlashMLA) |  Speedup |
| ---------------------| --: | ---: | ------------: | ---------------: | …

FlashMLA on CUDA

---

examples/imatrix/imatrix.cpp
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/cpy.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-cuda/mmvq.cuh
ggml/src/ggml.c
src/llama.cpp

In DeepSeek models there are two additional tensors, `*attn_k_b.weight` and `*attn_v_b.weight` required for MLA. When MLA is enabled, these will get used for attention computation. When standard attention is used, then the `*attn_kv_b.weight` tensors are used instead. Hence, when one has used standard attention to compute the imatrix, there will be no data for `*attn_k_b.weight` and `*attn_v_b.weight`; if one uses MLA, then there will be no data for `*attn_kv_b.weight`. As the `*attn_v_b.weight` tensors are simply the lower half of `*attn_kv_b.weight` (i.e., the second half of rows), they "see" the exact same activations as the `*attn_kv_b.weight` tensors. This PR takes advantage of this and enables the usage of `*attn_kv_b.weight` imatrix data for `*attn_v_b.weight` and vice versa.
The …

DeepSeek imatrix stuff

---

ggml/src/ggml-backend.c
ggml/src/ggml.c
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
src/llama.cpp

This PR improves the CPU implementation of FlashMLA in 3 ways:
* Faster prompt processing - about 13% improvement for a context of 16k tokens
* Smaller compute buffer size - about  60% reduction for a context of 128k tokens
To recall, FlashMLA-2 is enabled via `-mla 2 -fa`, and is the variant that works on the CPU and on CUDA.
The improvement is achieved by adding implementations for
* `ggml_mul_mat` where the second operand is not `fp32`
* `ggml_concat` where the operands are quantized
* `ggml_repeat` where the operand is not `fp32`
This allows us to avoid conversions to `fp32` that can become quite costly when operating on a very large context.
Here is a PP performance comparison for DeepSeek-Lite running on a Ryzen-7950X CPU between the main branch and this PR
| model                | …

FlashMLA-2 (CPU): faster and smaller compute buffer size

---

ggml/CMakeLists.txt
ggml/src/CMakeLists.txt
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/convert.cu

The `IQ2_KS, IQ2_K, ..., IQ6_K` quantization types do not have MMQ kernels, so matrix multiplications for model weights quantized with these types are done via dequantization to `fp16` and `cublasGemmEx` GEMM using `fp16` precision. For the DeepSeek series of MoE models this leads to NaNs.
Ideally I should add MMQ kernels for these quantization types. But for now, the PR provides a quick fix: dequantize to `bf16` and use `bf16` cuBLAS GEMM. This is added as a compile time option enabled via
```
cmake -DGGML_CUDA_IQK_FORCE_BF16 $other_cmake_options
```
(or, if you like me prefer using `ccmake`, after pulling the PR, `cmake .. && ccmake .`, and then set the `GGML_CUDA_IQK_FORCE_BF16` to `ON`). 
I have tested with DeepSeek-Lite quantized with `IQ4_KSS` and `IQ4_K`. In both cases I get NaNs …

Compile time option to use bf16 for quants without MMQ kernels

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/binbcast.cu
ggml/src/ggml-cuda/concat.cu
ggml/src/ggml-cuda/cpy.cu
src/llama.cpp

For DeepSeek-V3/R1 this reduces KV cache size by ~2 GiB for a context of 65k tokens.
Using
```
-amb 512 -mla 2 -fa -ctk q8_0
```
one should now be able to use 65k context with a single 24 GB GPU processing all attention calculations and all non-MoE expert tensors offloaded to it. See PR #260 for meaning and effect of the `-amb` command line option. 
There is still an issue with one or more  of the `GGML_OP_REPEAT, GGML_OP_CONCAT, GGML_OP_CPY` operations on CUDA, which are required to implement the entire attention computation using quantized tensors, so this PR takes the pragmatic approach of computing the attention operations with `fp16` on CUDA. The downside is that `fp16` will be used  also on the CPU if the code was built with CUDA enabled (and this is slower than using `Q8_0` …

Make Q8_0 KV cache work with FlasMLA-2 on CUDA

---

ggml/src/ggml.c

Somehow I had the concept that `Q8_0` KV cache is working for CPU-only inference with FlashMLA-2. Indeed it is for prompt processing, but not for TG (two different paths are taken). Clearly too many options as I'm getting confused myself. Anyhow, this PR adds the missing `Q8_0 -> Q8_0` contiguous transpose operation, so now we can use `Q8_0` KV cache with FlashMLA-2 also on the CPU.

Allow q8_0 cache on the CPU for FlashMLA-2

---

src/llama.cpp

The reason why `mmap` was disabled when using tensor overrides is this:
* When the command line argument is parsed (and the override buffer is set to `CPU`), we get  the buffer type returned by `ggml_backend_cpu_buffer_type()`
* The tensor loading logic uses `llama_default_buffer_type_cpu(true)` instead to see if a buffer is a CPU buffer and hence can be memory mapped.
* When CUDA (or some other backend) is enabled, `llama_default_buffer_type_cpu(true)` returns a different buffer type (`CUDA_Host` in the case of the CUDA backend).
* As a result, the tensors set to be stored in the CPU memory buffer are not memory mapped
This PR fixes that by asking the buffer type to be either `llama_default_buffer_type_cpu(true)` or `ggml_backend_cpu_buffer_type()` to be eligible for using `mmap`.
Note, …

Honor mmap setting when using tensor overrides

---

examples/quantize/quantize.cpp
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

The main purpose of this PR is to remove the need for run-time-repacking (command line argument `-rtr`) by having a tool to convert models to row-interleaved quantization types. The main motivation for providing this tool is to allow using `mmap` when loading a model and still having row-interleaved quants, so that one can combine the claimed performance gains from using 1 GiB huge pages (see #267) with the performance gains due to row-interleaved quants.
**Note:** this is only useful for **CPU-only** inference. The converted (repacked) model **will not work on a GPU** (or rather it will work but will be slow as all matrix multiplications with the repacked tensors will be done on the CPU).
To use it, simply
```
./bin/llama-quantize --repack some_model repacked_model some_quant
```
The …

Convert models to row-interleaved quants using the quantize tool

---

examples/quantize/quantize.cpp
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

For DeepSeek models `mla=1` has a very good TG but low PP performance. `mla=2` has better PP performance, but TG performance rapidly decreases with number of tokens in the KV cache. `mla=0` (i.e., standard attention) has the best PP performance, but TG is even lower than `mla=2`. In addition, standard attention requires a much larger KV cache than `mla = 1,2`. Here are two graphs comparing PP and TG performance of `mla=0,1,2` for DeepSeek-Lite. In all cases FA is enabled, the KV cache is quantized with `Q8_0`, the model weights are quantized with `IQ4_NL`, and the calculations are run on a Ryzen-7950X CPU. The second graph is TG speed as a function of the number of tokens in the KV cache (obtained using `llama-bench -gp Np,64`). Note the logarithmic x-axis for both graphs.
Since `mla=1` …

FlashMLA-3: the best of both worlds (CPU only)

---

examples/quantize/quantize.cpp
include/llama.h
src/llama.cpp

This PR follows in the footsteps of #272 and adds the ability to specify one or more regular expressions to use for matching tensor names to be repacked. This is useful for hybrid GPU/CPU inference where one will want to repack only the tensors that stay on the CPU.
Usage
```
./bin/llama-quantize --repack --repack-pattern regex1,regex2,... some_model output_file_name quant_type
```
E.g., if one uses tensor override `-ot exps=CPU` for inference to have the DeepSeek MoE experts stay on the CPU, one would use
```
./bin/llama-quantize --repack --repack-pattern exps some_model output_file_name quant_type
```
to repack an existing model.

Specify tensor name regex for tensors to be repacked

---

src/llama.cpp

This results in GGGGGGGGGGGGG when generating with mla = 3, fa = 0.
Likely also affects @saood06's benchmarking [here](https://github.com/ikawrakow/ik_llama.cpp/pull/273#issuecomment-2743023599)

Fix bug: missing parentheses in logical expression

---

convert_hf_to_gguf.py
gguf-py/gguf/constants.py
src/llama.cpp

Basically just the graph building. Conversion from safetensors needs to be done with upstream.

Add Gemma3 support (text only)

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
include/llama.h
src/llama.cpp

In #267 @orca-zhang observes significant performance gains using 1 GiB huge pages, so I decided to see if I can reproduce. 
This PR adds the option to use transparent huge pages (THP) on Linux. To use it, just add `-thp` to the command line (but note that it is only invoked if also `mmap` is being used).
I only have access to two remote Linux boxes, so I'm reluctant to try 1 GiB huge pages (as it requires a reboot to activate). Hence, my testing is done with the default 2 MiB huge page size. The other caveat is that my systems don't have enough RAM/disk space to try DeepSeek-R1, so testing with DeepSeek-Lite (same architecture, but just 16B parameters, so much smaller in size than DeepSeek-R1).
Results:
* On my Ryzen-7950X box I observe no real effect. If I run many times and average the …

Test transparent huge pages on Linux

---

ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp

@saood06 Can you try if this works better for your setup with `-mla 3 -fa`? Thanks.
There is a faster path for TG with FA and `mla=1,3`. But it only gets taken if some values are a multiple of the number of threads. This PR changes the implementation to also take the fast path when this is not the case. On a 32-core `AVX2` system I observe some speedup with 24 and 48 threads compared to main, so would be curious to know if this also improves things on a dual-socket system.

Attempt to improve FlashMLA on the CPU

---

ggml/src/iqk/iqk_mul_mat.cpp
src/llama.cpp

I was looking into the batched processing performance dips observed by @saood06 [here](https://github.com/ikawrakow/ik_llama.cpp/pull/277#issuecomment-2745952185) and I saw this for DeepSeek-Lite:
Commandline was
```
./bin/llama-batched-bench -m junk1.bin -npp 512 -ntg 128 -npl 4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76,80,84,88,92,96,100,104,108,112,116,120 -pps -fmoe -fa -mla 3 -t 16
```
It took me a while to figure out the reason for the dramatic drop in performance between a batch size of 16 and a batch size of 20. I was suspecting that something goes wrong how the work is being distributed between the threads. But at the end it turned out that it is due to the way the compute graph is built: when `n_token > n_head` we switch to "PP optimized" processing, which means we go …

Improve DeepSeek batched processing speed

---

ggml/src/ggml-cuda.cu

This PR makes "indirect" matrix multiplications as used for MoE models inference reproducible on CUDA, and closes #249 
As a bonus, we get a ~10% PP speedup as measured with DeepSeek-Lite. I wouldn't be surprised if the benefit is even larger for DeepSeek-R1 as it has 4X more experts than DeepSeek-Lite.
The culprit for non-reproducible results and sluggish performance was the `k_copy_src1_to_contiguous` kernel, where an atomic increment is used, which is slow, on top of making the order in which the `src1` rows are added to the contiguous copy random. This kernel is invoked `n_as` times, where `n_as` is the total number of experts, making the `mul_mat_id` implementation quite inefficient.

CUDA: better MoE implementation

---

examples/llama-bench/llama-bench.cpp

All applications in the `examples` folder except `llama-bench` accept `-t` (to specify number of threads for token generation) and `-tb` (to specify number of threads for prompt processing, a.k.a. prefill) as command line arguments. This is handy  because often TG peak performance is reached at a lower number of threads, so one wants to use that instead  of the number of cores, which is good for maximum prompt processing speed. `llama-bench`, inherited from upstream, has its own command line argument parsing, where one only has available `-t` but not `-tb`.
This PR adds a new command line argument to `llama-bench`: `-tgb` (or `--threads-gen-batch`).  One can use it as, e.g.,
```
./bin/llama-bench -tgb 4,16 -p 512 -n 128 other_arguments
```
where 4 threads will be used for the `tg128` …

llama-bench: enable having different number of threads for tg and pp

---

ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h

DeepSeek-V3/R1 gives NaNs when inference is run on a computer with `AVX512_VNNI` and the model is quantized with `Q8_0/Q8_0_R8` (issue #285). The difference to vanilla `AVX2` is that in that case activations are quantized with `Q8_1/Q8_1_X4`. The block scale and sum in `Q8_1/Q8_1_X4` are `fp16`.
We did have similar issues with `IQ1_S`, which was solved in #194 by going to a different quantization type for the activations. I did create issue #196 because of that.
We also observed NaNs on CUDA for `IQ4_K` and `IQ4_KS`. These quantization types do not have MMQ kernels, so matrix multiplications were done via dequantization to `fp16` and cuBLAS GEMM. The NaNs were resolved via dequantizing to `bf16` instead (PR #261)
So, it seems one can not use `fp16` arithmetic in DeepSeek-V3/R1.
This is …

Use bf16 instead of fp16 block scales for q8_1

---

ggml/src/ggml-quants.c

It is now more than a year since I added the imatrix to `llama.cpp`.  I think we can say that imatrix based quantization is now the standard. Hence, I believe it is no longer necessary to make quantization robust against failure modes that can be triggered when quantizing without an imatrix.
Based on this consideration, this PR adds improved versions of `make_qx_quants`, used to quantize `Q4_0, Q5_0, Q6_0, Q3_K, Q6_K`, and `quantize_row_iq4_nl_impl`, used to quantize `IQ4_NL` and `IQ4_XS`.
The following table shows PPL comparisons between the mai branch, this PR, and [PR 12557](https://github.com/ggml-org/llama.cpp/pull/12557) in mainline `llama.cpp` for LLaMA-v1-7B<sup>1</sup>(L1-7B in the table), LLaMA-v2-7B<sup>1</sup> (L2-7B), Mistral-7B<sup>1</sup> (M-7B), LLaMA-3.1-8B-Instruct …

Quantization improvements

---

ggml/src/ggml-quants.c
ggml/src/iqk/iqk_quantize.cpp

This PR is a follow up of #295. It applies the same approach to type-1 quants (`Q2_K, Q4_K, Q5_K, Q4_1, Q5_1`) and to `IQ3_K`. Quantization speed for `IQ3_K` is improved by a significant margin (up to 40%). Quantization speed for type-1 quants is also slightly improved ($\le 15$%). The changes do not result in PPL improvement for all tested models, but do improve PPL for the models that are more difficult to quantize (e.g., the LLaMA-3 series of models), and avoid a near catastrophic failure of `IQ3_K` on DeepSeek-Lite. 
The following table shows PPL comparisons between the main branch and this PR for LLaMA-v1-7B<sup>1</sup>(L1-7B in the table), LLaMA-v2-7B<sup>1</sup> (L2-7B), Mistral-7B<sup>1</sup> (M-7B), LLaMA-3.1-8B-Instruct (L3-8B), and DeepSeek-V2-Lite (DSL). Context is always 512 …

Quantization improvements (2)

---

ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
src/llama.cpp

Performance is not great, but it works with standard attentions and all 3 MLA options.
"Works" as:
* `f16` KV cache works for all combinations of `fa` and `mla`
* I have allowed only `Q8_0` quantized cache
* Quantized cache only works with standard attention (`-mla 0`) without FA
* With FA quantized cache kind of works, but we get messages such as `ggml_metal_get_buffer: error: tensor 'v-26' buffer is nil`. Not sure why. PPL is slightly higher than without FA

Metal: FA and FlashMLA

---

ggml/src/ggml-quants.c

The table shows PPL comparisons between the main branch and this PR for LLaMA-v1-7B<sup>1</sup>(L1-7B in the table), LLaMA-v2-7B<sup>1</sup> (L2-7B), Mistral-7B<sup>1</sup> (M-7B), LLaMA-3.1-8B-Instruct (L3-8B), and DeepSeek-V2-Lite (DSL). Context is always 512 tokens. Also given are the quantization times (Q-time for short in the table) in seconds on a Ryzen-7950X CPU. Tested is "pure" quantization (i.e., using the `--pure` option of `llama-quantize`) with token embeddings and output tensor set to `Q8_0`. The quantization command line is
```
./bin/llama-quantize --imatrix $imatrix --token-embedding-type q8_0 --output-tensor-type q8_0 --pure $model $output iq2_xs
```
| Model |  Quantization |  PPL (main) |  PPL (this PR) | Q-time (main) | Q-time (this PR) | …

Improved IQ2_XS quantization

---

include/llama.h
src/llama-vocab.cpp
src/llama.cpp

It seems the initial reactions to LlaMA-4 are mostly negative. Nevertheless, quantized LlaMA-Scout is something I can run on one of my systems, so here it is.
Derived from [PR 12791](https://github.com/ggml-org/llama.cpp/pull/12791) in mainline. But the code bases have diverged so much by now that it did take some effort to port the PR.
As with Gemma-3, I did not add the necessary modifications to `convert_hf_to_gguf.py`, so mainline is required to generate the model GGUF.
Did a quick test with a `Q6_K` model (no imatrix yet, so wanted to use more bits to not worry about quantization effects). Ryzen-5975WX CPU, RTX-4080 GPU, using
```
-ot exps=CPU -rtr -fmoe -t 32 -ngl 100
```
I got 221 t/s in the perplexity run, and 10.5 t/s for 128 tokens asking the standard question about the meaning …

LlaMA-4 support (text only)

---

src/llama.cpp

I was wondering about the hard-coded `1e-6` when porting the mainline PR, but left it the way it is. Mainline has now [corrected it](https://github.com/ggml-org/llama.cpp/pull/12882), so let's do that here as well.

Correct L4 rms_norm

---

examples/perplexity/perplexity.cpp

Some people insist that perplexity tells us nothing, and that [Kullback-Leibler Divergence](https://en.wikipedia.org/wiki/Kullback–Leibler_divergence) (KLD), along with the other statistics computed by `llama-perplexity` with the `--kl-divergence` option, are the one and only one true measure of quantization accuracy. Computing KLD requires 1st running the `llama-perplexity` tool with `--kl-divergence-base` to compute the logits of the base model, which are then used to compute KLD and other token probability statistics in a subsequent run with a quantized (or otherwise approximate) model. The base model logits file is quite large as it stores the log-probabilities for each evaluated token for all tokens in the vocabulary. Hence, when I added KLD capabilities to `llama.cpp` with …

Fix KLD precision

---

ggml/src/ggml-quants.c

I was experimenting with LlaMA-4-Scout quantization and was bothered by the extremely long quantization time of `IQ1_M`, so looked into speeding things up.
This PR improves `IQ1_M` quantization speed by a huge margin. There is also a minor improvement in quantization accuracy. 
The table shows PPL comparisons between the main branch and this PR for LLaMA-v1-7B<sup>1</sup>(L1-7B in the table), LLaMA-v2-7B<sup>1</sup> (L2-7B), Mistral-7B<sup>1</sup> (M-7B), LLaMA-3.1-8B-Instruct (L3-8B), and DeepSeek-V2-Lite (DSL). Context is always 512 tokens. Also given are the quantization times (Q-time for short in the table) in seconds on a Ryzen-7950X CPU. Unlike earlier quantization improvement PRs, which used "pure" quantization (`--pure` command line option in `llama-quantize`), tested is the …

Improved IQ1_M quantization

---

ggml/src/iqk/iqk_mul_mat.cpp

I constantly get confused how many `int16_t` dot products (`_mm256_maddubs_epi16()` results) I can sum up as `int16_t` before overflowing. In the case of `Q4_0` I was adding too few, and was having one unnecessary `_mm256_madd_epi16` because of that.  This PR fixes this. The result is a ~10% gain in performance when tested with Geema-3-12B-Instruct.

Better gemm/gemv on AVX2 fr q4_0_r8

---

ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_mul_mat.cpp

This PR adds improved TG performance on the CPU for GQA models (LLaMA-2+, Gemma, etc.).
We see performance gains with and without FA. The gains without FA are fairly minor and come from a different way of distributing the work between the threads for the `K*Q` and `V*softmax(K*Q)` matrix multiplications. The performance gains with FA enabled are very significant, and FA now outperforms no-FA also for TG.
Here is an example for LLaMA-3.1-8B-Instruct. Model is quantized with `Q4_0`, KV cache is `Q8_0` (V-cache is `f16` when FA is not enabled). Results are for a R$yzen-5975WX CPU (vanilla `AVX2`). Also included for comparison are mainline `llama.cpp` results (build 5139) with FA enabled shown with orange symbols. Results are obtained with `llama-sweet-bench` using
```
./bin/llama-sweep-bench …
```

Better TG performance for GQA models (CPU)

---

ggml/CMakeLists.txt
ggml/src/iqk/iqk_config.h
ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h

@ikawrakow
Sorry this is a mess, but this does get it to build now on my android device where I was able to replicate the compile error (my device does not support __ARM_FEATURE_DOTPROD so even though it now builds, it does not use the IQK stuff, but I may be able to confirm it works later on a device that that does support dotprod later).
I did catch the additional issue of the changed iqk_flash_attn_noalibi definition in the case where your building this repo and IQK_IMPLEMENT is not defined because my device doesn't support dotprod.
Fixes #159

Fix termux/android build

---

convert_hf_to_gguf.py
gguf-py/gguf/constants.py
gguf-py/gguf/tensor_mapping.py
src/llama.cpp

Very direct port of https://github.com/microsoft/BitNet/pull/167 more specifically this commit, https://github.com/Eddie-Wang1120/llama.cpp/commit/a8ac7072ae02ffd68b4b661db0ebd2689fb82b7f 
I had to do some minor additional fixes, it now compiles. 
I have not ran the model yet.

Add support for bitnet2b_2501 model

---

src/llama.cpp

Two small tweaks to #337:
* Use `create_tensor` instead of `ml.create_tensor`. This is necessary for tensor overrides to work (in case one would ever want to use tensor overrides with a BitNet model)
* Use `output.weight` instead of `token_embd.weight` for the final matrix multiplication. This improves CUDA performance quite a bit as `token_embd.weight` is on the host, so needs to be copied to the GPU each time it is needed (or the matrix multiplication is done on the CPU when running TG). I see that MicroSoft have decided to have `output.weight` stored in the model, even though it is identical to `token_embd.weight` (in the initial BitNet models one simply reused `token_embd.weight`). This makes the model quite a bit larger than it needs to be. Go figure.

BitNet adjustments

---

ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml-cuda/mmvq.cu

Based on [PR 13095](https://github.com/ggml-org/llama.cpp/pull/13095) in mainline. Did not measure, but had the impression that CUDA compile time is reduced.

cuda: use switch in constexpr funcs

---

ggml/src/ggml.c

When I changed the `vet_dot_type` for `q8_1_x4` to `q8_2_x4` for the quants using `q8_1_x4` I forgot to also make the change for the `ARM_NEON` implementation. As a result `q4_1` and `q5_1` are currently broken. But because `q4_0/q5_0` will use `q4_1/q5_1` for a few `ffn_down` layers, `q4_0` and `q5_0` are broken as well.
Looking at the implementation, changing to use `q8_2_x4` would be too a major change. Hence, just go back to using `q8_1_x4` on Arm. If this results in some models not working correctly, then simply don't use legacy quants for those models.

Fix q4_1 and q5_1 on Arm

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
src/llama.cpp

Closes #340
Rudimentary tests with [this model](https://huggingface.co/dranger003/c4ai-command-r7b-12-2024-GGUF/blob/main/ggml-c4ai-command-r7b-12-2024-q4_k.gguf), appears to work fine.
No attempt to update `convert_hf_to_gguf.py`, so ready GGUFs are required to use.

Add support for Cohere2

---

ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp

The bug was in the calculation of number of work items to use when computing FA on the CPU. In my case (maximum of 32 threads) it triggered with the GLM-4 model that has an unusually small number of KV heads (just 2). But I guess it can also trigger with a larger number of threads for more common numbers of KV heads.
Fixed by just using `max(1, nk)`. This will result in a far from optimal number of compute chunks, but at least it works.
I'm working on a better strategy for dividing the work between the threads on [this branch](https://github.com/ikawrakow/ik_llama.cpp/tree/ik/fattn_work_buffer),  but not quite ready for a PR yet.

Fix division by zero bug

---

ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_flash_impl.h
ggml/src/iqk/iqk_mul_mat.cpp

This PR further improves CPU FA performance for GQA models. It does not affect FlashMLA (relevant for DeepSeek models), but the same strategy could be applied also there. I have left this for a future PR.
Here some performance data and graphs for LLaMA-3.1-8B and Gemma3-12B. In all cases `Q8_0` quantized KV cache is used. The model weights are quantized with `Q4_0`, selected specifically because of having best performance in mainline `llama.cpp` due to the extraordinary amount of attention this quantization type receives.
<details>
<summary>Gemma3-12B, Ryzen-7950X CPU, mainline llama.cpp</summary>
|   512 |    128 |      0 |    4.855 |   105.46 | …

CPU FA improvements 

---

ggml/src/iqk/iqk_mul_mat.cpp

The bug was quite subtle: we have `Q8_0` K-cache, so we need to quantize the `Q` tensor to the appropriate quantization type (`vec_dot_type` in `ggml` lingo) that differs from platform to platform. We pick correctly the type. But then we notice that it is a GQA case, so we repack  the K tensor to `Q8_0_R8` for faster processing, but still use the `vec_dot_type` selected based on `K` being `Q8_0`. On `Zen4` and `ARM_NEON` the `vet_dot_type` is the same, so everything works fine. But on `AVX2` the `vec_dot_type` changes, and we get gibberish (or even an assert for a NaN value). 
The bug was introduced in my recent CPU FA optimization round (#351) 
Closes #363

Fix FA bug on AVX2

---

CMakeLists.txt

This commit is to prevent `tests\test-grammar-integration.cpp(483,13): error C2001: newline in constant` showing up in non-UTF8 windows system while using MSVC.

cmake: force MSVC compiler charset to utf-8

---

ggml/src/iqk/iqk_mul_mat.cpp

I got access to a Xeon Gold 6226R system. The PR fixes the compilation errors due to this CPU supporting all `AVX512` extensions necessary to define `HAVE_FANCY_SIMD`, but does not support SIMD `popcnt`.
After fixing the build, I did a quick test with Gemma3-27B-It. It is a dual-socket system, but even without `numactl` and without dropping caches I get quite respectable results:
```
./bin/llama-sweep-bench -m /LLM/google_gemma-3-27b-it-Q8_0.gguf -c 4096 -t 32 -fa -rtr
```
|   512 |    128 |      0 |    9.622 |    53.21 |   47.765 |     2.68 |
|   512 |    128 |    512 |    8.314 |    61.58 |   24.781 |     5.17 |
|   512 |    128 |   1024 | …

Fix build for Xeon Gold 6226R

---

ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_mul_mat.cpp

Nobody has used `ik_llama.cpp` with a DeepSeek model and `Q8_0` KV cache since PR #351?
This PR fixes the assert one gets when one tries to use a DeepSeek model on the CPU using `Q8_0` KV cache.
Also, it seems the optimization I added in #351 to repack the `K` cache to `Q8_0_R8` seems to lower TG performance for DeepSeek models, so disabling it.

Fix DeepSeek q8_0 cache

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/fattn-new-mma.cu
ggml/src/ggml-cuda/fattn-new-mma.cuh
ggml/src/ggml-cuda/fattn.cu
ggml/src/ggml-cuda/mmvq.cu

[This PR](https://github.com/ggml-org/llama.cpp/pull/13306) in mainline `llama.cpp` is a CUDA flash attention (FA) implementation that also works with K head size of 576 and V head size of 512 as required for DeepSeek models with MLA enabled. **Caveat: it only works on Ampere or newer Nvidia GPUs**.
I have taken it and adapted it to the `ik_llama.cpp` environment, but only using it for the 576,512 case (for other head sizes it is slower than the existing implementation). This allows to finally have `-mla 3 -fa`, which is the recommended option for DeepSeek models when running on the CPU, also work on CUDA.
This results in massive DeepSeek TG performance gains for long contexts when self attention is computed on the GPU. The graph below shows an example for `Q4_0` quantized DeepSeek-Lite …

FlashMLA-3 for DeepSeek models on CUDA

---

ggml/src/ggml-cuda/fattn-new-mma.cu

The implementation was assuming that the K and V cache are contiguous, and was using this assumption to dequantize to `fp16`. This is certainly wrong for the V cache, which is just a view of the K cache with rows of 512 instead of 576 elements.
@JohannesGaessler You may want to take a look at this PR. I don't think your [PR in mainline llama.cpp](https://github.com/ggml-org/llama.cpp/pull/13306) can work for DeepSeek models with quantized KV cache.
A test session with [this model](https://huggingface.co/bartowski/DeepSeek-V2.5-1210-GGUF/tree/main/DeepSeek-V2.5-1210-IQ3_XXS):
```
./bin/llama-cli -m ./ds2.5/DeepSeek-V2.5-1210-IQ3_XXS-00001-of-00003.gguf -t 32 -ngl 100 -mla 3 -fa -c 32768 -s 1234 -ot exps=CPU -cnv -ctk q8_0 -ctv q8_0
```
<details>
<code>
ggml_cuda_init: GGML_CUDA_FORCE_MMQ: …

Fix CUDA DeepSeek FlashMLA-3 with quantized KV cache

---

src/llama.cpp

Mainline `llama.cpp` [PR 12801](https://github.com/ggml-org/llama.cpp/pull/12801), which added MLA support for DeepSeek models 2.5 months after MLA was available here, broke backwards compatibility. As a result, the new DeepSeek GGUFs that started appearing on HF are not compatible with `ik_llama.cpp`, resulting in issues #373 and #383.
My initial reaction was to not support the new DeepSeek GGUFs, as there was no real reason to introduce the backwards incompatibility (and have people re-download the giant DeepSeek-R1/V3 models). The two new tensors (per layer) required for MLA can be easily created on-the-fly when loading the model as it is done here.
But after some more thought I decided to handle the incompatible GGUFs, and this functionality is added with this PR.
I have tested with …

Handle incompatible DeepSeek GGUFs

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml.c

This PR does 3 things:
* Removes an unnecessary device to host copy of selected experts IDs on CUDA. This results in a few percent improvement of CUDA TG speed for MoE models
* Fixes bugs related to Smart Experts Reduction (SER, see #239). The issue was that the `GGML_OP_GET_ROWS` op implementation did not consider disabled experts for float tensors. As a result, when combining the results of the experts garbage weights were used for the disabled experts, which could lead to NaNs.  
* Further improves CUDA TG performance with SER enabled. Here the `ggml_cuda_op_mul_mat_vec_q_id` function did not consider that an expert may be disabled, and needlessly calculated the matrix-vector multiplication for disabled experts.
Prompt processing is not eaffected by these changes.
Here is a graph …

TG improvements for MoE models

---

ggml/src/ggml-cuda/fattn-new-mma.cu

Reference: https://github.com/ggml-org/llama.cpp/pull/13438

Fix race in the CUDA DeepSeek FA kernel

---

common/common.cpp
common/common.h
ggml/include/ggml-backend.h
ggml/src/ggml-backend.c
ggml/src/ggml-cuda.cu
include/llama.h
src/llama.cpp

When part of the tensors are stored in RAM but there are faster back-ends available (GPU), the scheduler needs to decide if to offload the data for a given op to a faster back-end or to compute the op on the CPU. This is currently done via a simple heuristics where only matrix multiplications (`GGML_MUL_MAT` and `GGML_MUL_MAT_ID`) are offloaded if the batch size is larger than some threshold (currently 32). When `fmoe` is enabled, the fused `(ffn_up*X)*unary(ffn_gate*X))` op is never uploaded. In contrast, in mainline `llama.cpp` matrix multiplications are always offloaded when the batch size is `>= 32`. The result of this is that when the batch size becomes large enough, `llama.cpp` will outperform `ik_llama.cpp` in prompt processing speed. As "large enough" depends on many factors (size …

GPU offload policy

---

ggml/src/CMakeLists.txt
ggml/src/ggml-cuda/cp-async.cuh
ggml/src/ggml-cuda/fattn-new-mma.cu
src/llama.cpp

This is a port of [this PR](https://github.com/ggml-org/llama.cpp/pull/13435) in mainline `llama.cpp`.
The main difference to PR #386 is that now the FA kernel takes advantage of the fact that the V tensor contains the same data as the K tensor (it is a view on the K cache with an offset given by the RoPE embedding size). Hence, one can reduce the number of loads by reusing K tiles when processing `V*softmax(K*Q)`.
To take advantage of this new kernel I had to change the way the K cache is organized. In mainline `llama.cpp` the K cache stores `(RoPE, NoPE)` parts in that order, and the FA kernel assumes this arrangement. But in `ik_llama.cpp` prior to this PR the K cache was stored as `(NoPE, RoPE)`. As there are several places where the views into the K cache can go wrong when building …

Faster DeepSeek FA on CUDA

---

common/common.cpp
include/llama.h
src/llama.cpp

Mainline llama.cpp [PR 12901](https://github.com/ggml-org/llama.cpp/pull/12801), which added MLA support for DeepSeek models 2.5 months after MLA was available here, broke backwards compatibility. As a result,
the new DeepSeek GGUFs that started appearing on HF became compatible with `ik_llama.cpp`, so I added support for the incompatible GGUFs in #394. But using such crippled DeepSeek GGUF results in a much lower prompt processing performance. This is because the `attn_wkv_b` tensor is missing, so one cannot use `mla = 3`.
This PR removes this limitation. When `-mla 0 or 2 or 3` is specified on the command line, missing `attn_wkv_b` tensors are created on-the-fly while loading the model. This is basically the reverse of #259, where the `attn_wk_b` and `attn_wv_b`tensors necessary for MLA …

Enable faster prompt processing with mainline llama.cpp GGUFs

---

common/common.cpp
common/common.h
examples/sweep-bench/sweep-bench.cpp

When using `sweep-bench` on CUDA, often the PP performance for `N_KV = 0` (i.e., first PP run) is lower than the measured PP performance for `N_KV > 0`. My guess is that this is due to having to find and load from the cache of pre-compiled kernels the required once, which may take time that is not negligible compared to the time it takes the compute the batch. For an example, see the graph in PR #374.
To prevent this misleading result, this PR adds the ability to also use a warm-up run with `n_ubatch` tokens.  The option is off by default as computing a batch on the CPU for a large model can take a significant amount of time (but the measured performance is not affected by having done a batch warmup run). To turn it on, use
```
./bin/llama-sweep-bench --warmup-batch (or -wb) …
```

Add batch warmup to sweep-bench

---

ggml/src/ggml-cuda/fattn-new-mma.cu

Fix new CUDA FA on Touring

---

ggml/src/iqk/iqk_mul_mat.cpp

This FA tweak improves DeepSeek-Lite CPU TG performance with `Q8_0` KV cache.
Not sure if it will have a positive impact for the large DeepSeek models. To optimize the FA strategy for those I need to be able to test, which I cannot atm.
The graph shows a comparison between the main branch and this PR for a `Q4_0` quantized DeepSeek-Lite model. The CPU is Ryzen-7950X. The x-axis is `N_KV/1000`, where `N__KV` is the number of tokens in the K cache, which is quantized with `Q8_0`. The `sweep-bench` command was
```
./bin/llama-sweep-bench -m $model -c 16384 -ub 1024 -t 16 -mla 3 -fmoe -fa -rtr
```
<details>
<summary>Main branch</summary>
|  1024 | …

Better CPU FA performance for DeepSeek-Lite

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp

There have been reports that Smart Expert Reduction (SER) can produce garbage.
This PR (hopefully and finally) fixes the CPU implementation.
The issue was that when fewer experts are used than specified by the number of active experts, there are some rows in the experts matrix multiplication results that have not been set to any value. Normally this should not be an issue as these rows get multiplied by zero before being summed up to obtain the final experts result. But if there are `Inf` or `NaN` values in the rows that were not computed, then we get NaNs, and this leads to garbage output. If there are `Inf` and `NaN` values is a matter of luck that depends on what happened before in the computation, as the same memory is used by other operations to store results. This is why the issue …

Fix SER (CPU)

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml.c

Follow up of #415. This should fix SER issues on CUDA.

Fix SER (CUDA)

---

examples/quantize/quantize.cpp
ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/common.cuh
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmq.cu
ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml-cuda/mmvq.cu
ggml/src/ggml-metal.m
ggml/src/ggml-metal.metal
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h
include/llama.h
src/llama.cpp

For motivation, see the CUDA performance graphs in #417 and #418.
Implementation for `AVX2, Zen4, ARM_NEON, CUDA, Metal`.
The `AVX2` implementation suffers from `int16_t` overflow, and so do the `IQ4_K, IQ5_K, IQ6_K` and `IQ4_KS`, so I will have to fix all of these in a follow up PR.
I also want to add interleaved variant `IQ5_KS_R4` before giving more performance and accuracy details.

Adding IQ5_KS - 5.25 bpw quants

---

ggml/src/iqk/iqk_mul_mat.cpp

I have made the exact same mistake a number of times.
On `AVX2` the instruction to perform dot products of `int8_t` vectors (as needed in quantized matrix multiplications) is `_mm256_maddubs_epi8(x, y)`, where `x` must be unsigned and `y` signed, and the result is a SIMD vector of signed `int16_t` values $z_i = x_{2i} y_{2i} + x_{2i+1} y_{2i+1}$. The quant values `x` and quantized activations `y` are signed, so one way to deal with the the strangeness of this instruction is to add a suitable constant value `c` to `x` so that it becomes unsigned, use `_mm256_maddubs_epi8(c+x, y)` to accumulate the dot product, and at the end subtract $c \cdot b$, where $b = \sum y_i$ has been pre-computed when quantizing the activations `y`. The issue arises when the `x` values span the full `int8_t` range …

Fix AVX2 implementation of IQ4_K, IQ4_KS, IQ5_K, IQ6_K

---

ggml/src/iqk/iqk_mul_mat.cpp

| model            |       size | threads |          test |     t/s (main)   |      t/s (PR) |  Speedup |
| ---------------- | ---------: | ------: | ------------: | ---------------: | ------------: | -------: |
| llama 8B IQ2_KS  |   2.46 GiB |      16 |         pp512 |    179.51 ± 1.13 | 196.20 ± 1.59 |  1.093   |   
| llama 8B IQ4_KS  |   4.14 GiB |      16 |         pp512 |    172.36 ± 1.28 | 198.57 ± 1.74 |  1.152   |   
| llama 8B IQ5_KS  |   4.95 GiB |      16 |         pp512 |    150.93 ± 1.61 | 196.20 ± 1.59 |  1.300   |

Zen4: Faster PP for IQ2_KS, IQ4_KS, IQ5_KS

---

ggml/src/ggml-cuda/mmq.cuh

Forgotten MMQ ref and typo

---

examples/gguf-split/gguf-split.cpp

Among the useful stuff on mainline, there's the updates of gguf-split.
I encountered some crashes on my KCPP fork reading the split ggufs made with IK Llama back in January. I thus merged these two commits in my IK_Llama fork to produce my split ggufs, and the crashes were gone in my KCPP fork. I kept using this ever since.
Those two commits are pre-GGUF v14 refactor, and there was not a single conflict with the merge, nor problem to compile on the current IK_LLama.
So I just put it here!
-----
gguf-split : improve --split and --merge logic (#9619)
* make sure params --split and --merge are not specified at same time
* update gguf-split params parse logic
* Update examples/gguf-split/gguf-split.cpp
Co-authored-by: Xuan Son Nguyen <thichthat@gmail.com>
Co-authored-by: slaren …

gguf-split : update

---

ggml/src/ggml-cuda/mmvq.cu

After a very long bug hunt, this PR should hopefully fix #389, #398, #425.
Thanks to everybody who tested my previous bug fix attempts!
Huge kudos to @ciprianveg who was instrumental in finding the bug!
The bug was in the CUDA matrix-vector multiplication kernel (a.k.a., MMVQ). It only shows up when the kernel processes 2 or 3 tokens. Hence, it was not observed during TG, and only showed up during PP when an expert in a MoE model ended up with having to process just 2 or 3 tokens from the batch (which is rare).
I believe all other changes I made in #442 are not necessary, but please test this PR to confirm.
Closes #389 
Closes #398
Closes #425

Fix bug in MMVQ kernel

---

convert_hf_to_gguf.py
ggml/src/ggml-cuda/mmvq.cu
src/llama.cpp

This, notably in order to make smaller conversions to generate an iMatrix file.
`Q4_0`,`Q4_1` are here using embeddings, output, attn_k and attn_v in q5_0.
`Q5_0`,`Q5_1` are here using embeddings, output, attn_k and attn_v in q8_0.
Adapted from the following llama.cpp mainline PR : https://github.com/ggml-org/llama.cpp/pull/9022 Original author @chentyjpm
Reason : Even in pure q4_0, an iMatrix is viable (much less than 0.01 ppl difference with a q8_0 one on the final quantization made with the created iMatrix).
Those schemes are thus pertinent imho.
I personally use the q5_0 scheme to make my iMatrixes for the L3 70b models, and the ppl difference is less than 0.005 on the final quantized model with iMatrix, this compared to an f16 iMatrix made by Bartowski or Mradermacher.
Also, 2 …

Legacy quants conversion schemes in convert_hf_to_gguf.py

---

gguf-py/gguf/constants.py

The recently added `IQ5_KS, IQ5_KS_R4, IQ2_KT, IQ3_KT, IQ4_KT` were missing.

Add missing gguf-py constants

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu

The `IQX_K` quants and their row-interleaved siblings `IQX_K_R4` offer better quantization quality than corresponding i-, k-, or legacy quants at the same bpw. `IQX_K_R4` quants have better CPU performance but cannot be used on CUDA as there is no GEMM/GEMV implementation. Hence, "quant cookers" need to release `IQX_K` quantized model, so users can use them on their GPUs, but that requires users doing CPU-ony inference to repack the model to take advantage of the better CPU performance. In addition, @ubergarm has released various `IQK_X_R4` quantized models (see [here](https://huggingface.co/ubergarm), and those cannot be used for GPU inference. 
To remove such inconvenience, this PR adds CUDA implementation for the row-interleaved quants `IQ2_K_R4, IQ3_K_R4, IQ4_K_R4, IQ5_K_R4`. I'll …

CUDA implementation for IQ2_K_R4, IQ3_K_R4, IQ4_K_R4, IQ5_K_R4

---

ggml/src/ggml.c
ggml/src/iqk/iqk_gemm_ktquants.cpp
ggml/src/iqk/iqk_mul_mat.cpp

Alternative to #460 
One wouldn't really want to use this on a NEON CPU as it is much too slow. But for the sake of completeness, here it is.
Sweep bench results for LLaMA-3.1-8B-Instruct **with BLAS** on M2-Max CPU (PP performance is much lower without BLAS)
|   512 |    128 |      0 |    5.364 |    95.44 |   11.527 |    11.10 |
|   512 |    128 |    512 |    4.644 |   110.25 |   11.739 |    10.90 |
|   512 |    128 |   1024 |    4.870 |   105.14 |   12.270 |    10.43 |
|   512 |    128 |   1536 |    5.055 |   101.29 |   12.644 |    10.12 |
|   512 |    128 |   2048 |    5.289 |    96.81 |   12.732 |    10.05 |
|    PP |     TG |   N_KV |   T_PP …

NEON implementation for trellis quants

---

src/llama.cpp

Tested and was able to successfully read and write the cache to a file. De-fragmenting the cache still has yet to be tested.
It does currently does list the KV size twice (see below), and this seems like a minor regression to me but wanted to ask before I changed it.
```
llama_new_context_with_model: KV self size  = 5369.91 MiB, K (f16): 5369.91 MiB, V (f16):    0.00 MiB
llama_new_context_with_model: KV self size  = 5369.91 MiB, c^KV (f16): 5369.91 MiB, kv^T: not used
```

Replace MLA-specific KV cache with the standard KV cache V2

---

convert_hf_to_gguf.py
gguf-py/gguf/quants.py
gguf-py/tests/test_quants.py

This quantization script is obtained by making a sort of "cross multiplication" with the python code for q5_0, and the C code for q5_0 and q6_0 in order to get through trial and error the code for the q6_0 conversion script, this with the help of a 7xB parameters AI model.
It was an interesting experiment!
Tested on Llama 3.2 instruct 1B and Qwen 2.5 instruct 1.5B.
Bitrate of this q6_0 conversion is 6.50BPW straight.
PPL equivalent (+/-0.5%) to a regular q6_0 quant from a fp16 gguf.
Inference is working as intended in my Croco.cpp.

 convert_hf_to_gguf.py : conversion from hf weights to Q6_0

---

common/common.cpp
common/sampling.cpp
common/sampling.h
examples/main/README.md
examples/server/README.md
include/llama.h
src/llama-sampling.cpp
src/llama-sampling.h
src/llama.cpp

Given popular demand, adding top-n $\sigma$ sampler.
Set to off by default.
* Add to sampling chain using `--sampling-chain ...n...` or `--samplers ...top-n-sigma...`
* Set parameter using `--top-n-sigma value`

Adding top-n-sigma sampler

---

ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/convert.cu
ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/iqk_mmvq.cuh
ggml/src/ggml-cuda/mmvq.cu

To help the quest for the world's smallest DeepSeek model, this PR adds CUDA implementation for `IQ1_M_R4`.
GEMM is done via dequantize+cuBLAS, so may require `cmake -DGGML_CUDA_IQK_FORCE_BF16=ON`.
Performance is on par or even tiny bit better than `IQ1_M`.
Here sweep bench for LlaMA-3-8B on RTX-4080
|  2048 |    512 |      0 |    0.347 |  5909.51 |    2.466 |   207.66 |
|  2048 |    512 |   2048 |    0.329 |  6216.59 |    2.657 |   192.69 |
|  2048 |    512 |   4096 |    0.356 |  5745.00 |    2.928 |   174.88 |
|  2048 |    512 |   6144 |    0.384 |  5332.11 |    3.162 |   161.91 |
|  2048 |    512 |   8192 |    0.411 |  4983.68 |    3.380 | …

IQ1_M_R4 CUDA implementation

---

examples/server/server.cpp

Now that saving the prompt cache works this adds a way to query all the currently saved prompt caches.
This should be enough to be used by any front end. The only thing that may potentially be useful to be added is giving the prompt in an array based on how the prompt is tokenized.

Add an endpoint that lists all the saved prompt caches to server

---

ggml/src/iqk/iqk_gemm_iquants.cpp

Closes #523 
@ciprianveg  @Ph0rk0z
Does this work better for you?

Perhaps a slightly better GEMV version for IQ2_XXS, IQ3_XXS, IQ3_S

---

ggml/src/ggml.c
ggml/src/iqk/iqk_gemm_kquants.cpp
ggml/src/iqk/iqk_gemm_kquants.h
ggml/src/iqk/iqk_gemm_legacy_quants.cpp
ggml/src/iqk/iqk_mul_mat.cpp

These two quantization types are quite popular, so I thought it makes sense to improve their performance. The repacked variants `Q4_K_R4` and `Q5_K_R4`  do not have a CUDA implementation, so repacking is not useful in a hybrid CPU/GPU setup where it may be better to offload tensors stored in RAM to the GPU when processing large batched.
The PR uses the same trick as #515, #516, #517, #518. When processing batches `>= 32` tokens, `Q4_K` or `Q5_K` quantized tensors are repacked on-the-fly to `Q8_1_R8`. 
Here some sweep-bench results for LLaMA-3.1-8B-Instruct on a Ryzen-7950X CPU
|   512 |    128 |      0 |    2.853 |   179.49 |    9.792 |    13.07 | …

Faster CPU prompt processing for Q4_K and Q5_K

---

ggml/src/iqk/iqk_mul_mat.cpp

When adding the faster GEMM in #524 / #525 I forgot to add the call to `iqk_convert_repack` also in the MoE matrix multiplication functions, which causes a crash (see #527). This PR fixes it.

Fix bug introduced in #524/#525

---

ggml/src/ggml.c
ggml/src/iqk/iqk_gemm_iqk_quants.cpp
ggml/src/iqk/iqk_gemm_iqk_quants.h
ggml/src/iqk/iqk_mul_mat.cpp

This PR is a follow up of #531 and applies the technique to `IQK` quants.
Here is a PP-512 performance comparison for LlaMA-3.1-8B-Instruct on a Ryzen-7950X CPU between the main branch and this PR:
| model            |       size |          test |     t/s (main)   |    t/s (PR)      |   Speedup |
| ---------------- | ---------: | ------------: | ---------------: | ---------------: | --------: |
| llama 8B IQ2_KS  |   2.05 GiB |         pp512 |    203.08 ± 0.39 |    372.48 ± 3.69 |  1.834    |    
| llama 8B IQ2_K   |   2.22 GiB |         pp512 |    195.04 ± 2.44 |    365.58 ± 4.25 |  1.874    |    
| llama 8B IQ3_K   |   3.21 GiB |         pp512 |    167.65 ± 0.53 |    354.90 ± 3.44 |  2.117    |    
| llama 8B IQ4_KS  |   3.98 GiB |         pp512 |    198.28 ± 0.57 |    362.81 ± 1.74 | …

Much faster CPU prompt processing (part 2)

---

ggml/src/iqk/iqk_gemm_kquants.cpp
ggml/src/iqk/iqk_gemm_legacy_quants.cpp
ggml/src/iqk/iqk_gemm_legacy_quants.h
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp

This PR is a follow up of #531 and #533, and adds much faster GEMM for the remaining non-interleaved quants: `Q2_K, IQ4_XS, IQ4_NL, Q4_0, Q4_1, Q5_0, Q5_1, Q6_0, Q8_0`.
Here is a PP-512 performance comparison between the main branch and this PR for LLaMA-3.1-8B-Instruct on a Ryzen-7950X CPU:
| type | main (t/s)  | PR (t/s)  | Speedup |
| Q2_K   | 202.1 | 364.2 | 1.802 |
| IQ4_XS | 178.0 | 363.2 | 2.040 |
| IQ4_NL | 136.6 | 293.5 | 2.149 |
| Q4_0 | 155.6 | 300.9 | 1.934 |
| Q4_1 | 135.1 | 253.5 | 1.876 |
| Q5_0 | 147.5 | 293.4 | 1.989 |
| Q5_1 | 124.9 | 253.5 | 2.030 |
| Q6_0 | 129.0 | 296.2 | 2.296 |
| Q8_0 | 145.9 | 293.5 | 2.012 |
We observe gains in the range of 2X for all types. In case anyone is wondering why we see 3 performance levels, this is simply …

Much faster CPU prompt processing (part 3)

---

ggml/src/iqk/iqk_gemm_ktquants.cpp

Removes errant ";" in front of 0xCBAC1FED in non-x86 code
```
error: expected primary-expression before ';' token
constexpr static uint32_t ka = ;0xCBAC1FED;
^
error: expected unqualified-id before numeric constant
constexpr static uint32_t ka = ;0xCBAC1FED;
^
```

Fix KT Neon / ARM typo

---

ggml/src/iqk/iqk_gemm_legacy_quants.cpp

See #538
The story behind this bug:
Many years ago, the committee designing the `AVX` instruction set decided to use the most unhelpful instruction for performing dot products between `int8` SIMD vectors: the left operand in the instruction had to be an unsigned integer. That decision propagated into `AVX2` and `AVX512`. When using this in the context of quantized LLMs, where quantized model weights are signed integers, we have two options to deal with this situation: 
1. Remove the signs of the left operand and apply the same signs to the right operand
2. Add a constant to the left operand such that it becomes unsigned. Undo the applied constant by subtracting the constant times the sum of the quants in the right operand
Option 2 is faster, but cannot be used on `AVX2` when the quants …

Fix missed block_q8_x2 bf16 -> i16 change

---

ggml/src/iqk/iqk_gemm_ktquants.cpp
ggml/src/iqk/iqk_mul_mat.cpp

The PR adds some optimizations to the GEMV implementation of the `IQ2_KT, IQ3_KT, IQ4_KT` quants.
On my Ryzen-7950X I don't notice much of a difference when running with 16 threads as the calculation is (nearly) memory bound. But when testing with fewer threads, I see quite significant gains in TG performance compared to the main branch. Here some results for LlaMA-3.1-8B-Instruct
| model             |       size | threads |          test |      t/s (main)  |     t/s (PR)     |  Speedup |
| ----------------- | ---------: | ------: | ------------: | ---------------: | ---------------: | -------: |
| llama 8B IQ2_KT   |   2.77 GiB |       2 |         tg128 |      3.28 ± 0.00 |      4.11 ± 0.00 |   1.253  |
| llama 8B IQ2_KT   |   2.77 GiB |       4 |         tg128 |      6.28 ± 0.01 | …

Perhaps slightly faster trellis quants

---

ggml/src/ggml.c
ggml/src/iqk/iqk_gemm_iquants.cpp
ggml/src/iqk/iqk_gemm_kquants.cpp
ggml/src/iqk/iqk_mul_mat.cpp

It is time to give some attention to the `ARM_NEON` back-end, which has fallen behind quite a bit.
This PR corresponds to PRs #531, #533, #534, #546, #549, #550, and applies the on-the-fly repacking technique to k-quants (`Q2_K,  Q3_K, Q4_K, Q5_K, Q6_K`) and to `IQ4_XS` for the `ARM_NEON` implementation.
Here is a PP-512 performance comparison between the main branch and this PR for LlaMA-3.1-8B-Instruct on M2-Max
| type |  t/s (main) | t/s (PR) | Speedup |
| Q2_K | 85.74 | 168.07 | 1.960 |
| Q3_K | 45.68 | 170.83 | 3.740 |
| Q4_K | 58.24 | 114.78 | 1.971 |
| Q5_K | 54.88 | 114.92 | 2.094 |
| Q6_K | 47.67 | 123.98 | 2.601 |
| IQ4_XS | 71.19 | 167.84 | 2.358 |
`Q2_K, Q3_K` and `IQ4_XS` join the top-tier group in terms of prompt processing speed.
`Q4_K` and …

Much faster prompt processing for k-quants (ARM_NEON)

---

include/llama.h
src/llama-vocab.cpp
src/llama.cpp

Closes #551 
How to use:
1. Grab a GGUF containing Microsoft's `i2_s` quant packing. E.g.,
```
huggingface-cli download --local-dir falcon tiiuae/Falcon-E-3B-Instruct-GGUF
```
2. Convert to `ik_llama.cpp` quants `iq2_bn` or `iq1_bn`. `iq2_bn` uses 2 bits per weight (bpw), `iq1_bn` uses 1.625 bpw. `iq2_bn` is faster for prompt processing, and may also be faster for token generation (TG) on devices with limited computing power. `iq1_bn` uses 20% less RAM, so that if TG is memory bound, it will be slightly faster than `iq2_bn`. Command to convert is
```
./bin/llama-quantize --allow-requantize falcon/ggml-model-i2_s.gguf falcon_iq2_bn.gguf iq2_bn 
```
(replace `iq2_bn` with `iq1_bn` if you prefer the smaller variant.
3. Utilize the just created model file in the usual way with `llama-cli, …

Add Falcon-Edge support

---

ggml/src/ggml-cuda/mmq.cu

While working on #557 I noticed that dequantize+cuBLAS is faster than MMQ for the `iqX_k_r4` quants when the batch size is larger than some threshold.
The same applies to all quantization types with block size of 16: `Q2_K, Q3_K, Q6_K, IQ2_XS, IQ2_S, IQ2_K, IQ3_K, IQ4_K, IQ5_K, IQ6_K`. Hence, this PR changes the `ggml_cuda_should_use_mmq()` function to return `false` if the batch size (number of rows in the right matrix) is greater than some quantization type specific threshold.
This graph illustrates the PP performance improvement achieved this way for k-quants. Model is LlaMA-3.1-8B-Instruct, GPU is RTX-4080, and in all cases pure quantization is used. `Q2_K` appears to have a particularly bad MMQ implementation (I need to look into that more closely), so there we benefit from switching …

Use cuBLAS for large batches and quants with block size 16

---

ggml/src/CMakeLists.txt
ggml/src/ggml-backend.c

The Vulkan stuff had ended up outside the `if (GGML_VULKAN)` condition, which prevents building any configuration unless having Vulkan installed.
This PR fixes it.
Oh, it shows as 130 lines changed because I retabed (don't like having tabs in source code). The change is much smaller in reality.

Fix CMakeLists

---

ggml/include/ggml.h

This is needed by the Vulkan back-end when coopmat2 is enabled.
It is 64 in mainline too.

Change KQ mask padding to 64

---

common/sampling.cpp
src/llama.cpp

Do not crash when there is no DRY sampler

---

ggml/src/ggml-vulkan.cpp
ggml/src/vulkan-shaders/fused_mul_gelu.comp
ggml/src/vulkan-shaders/fused_mul_relu.comp
ggml/src/vulkan-shaders/fused_mul_silu.comp
ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp
src/llama.cpp

The tiniest of performance increases, barely measurable.
But now we no longer need to special-case Vulkan when building the graph.
Of note: I went to measure mainline `llama.cpp` Vulkan performance with my setup (RTX-4080 in a Ryzen-5975WX box, Nvidia driver 575, so coopmat2 enabled). Interestignly enough, `ik_llama.cpp` is 10-15% faster than mainline for a context of 16k tokens, even though there aren't any noticeable Vulkan optimizations in `ik_llama.cpp` yet. Is mainline paying the price for the grand KV cache unification?
Here sweep-bench results for LlaMA-3.1-8B-Instruct
|  1024 |    256 |      0 |    0.244 |  4200.63 |    2.742 |    93.37 | …

Vulkan: add GGML_OP_FUSED_MUL_UNARY

---

ggml/src/ggml-vulkan.cpp
ggml/src/vulkan-shaders/flash_attn.comp
ggml/src/vulkan-shaders/flash_attn_base.comp
ggml/src/vulkan-shaders/flash_attn_cm1.comp
ggml/src/vulkan-shaders/flash_attn_cm2.comp

This PR is a cherry-pick of [PR 14509](https://github.com/ggml-org/llama.cpp/pull/14509) in mainline `llama.cpp` with minor adaptations, and adds FA for the DeepSeek models to the Vulkan back-end.
* The batch size cannot be greater than the maximum context length. Under normal usage this is never the case, but if one runs `perplexity` with default parameters where context is set to 512 tokens while batch size is 2048 tokens, one gets NaNs after the first context chunk. I have spent the better part of of the day trying to understand the reason, and just don't see it. Almost prepared to give a bounty to the person who finds the bug. 
* For now KV cache can only be `fp16` as I have not implemented the various additions required to make quantized cache work with DeepSeek models in the Vulkan …

Vulkan: flash attention for DeepSeek models

---

convert_hf_to_gguf.py
convert_hf_to_gguf_update.py
include/llama.h
src/llama-vocab.cpp
src/llama.cpp

Needed this for some quants and realized it didn't support it already, so figured I'd just PR upstream  
Seems a bit odd to need to figure out model families by vocab size? But I'm not sure of a better way to do it, so left it as-is for now

Special handling of Seed Coder FIM tokens

---

include/llama.h
src/llama-vocab.cpp
src/llama.cpp

Based this PR on mainline https://github.com/ggml-org/llama.cpp/pull/14425. Didn't merge any python stuff (used mainline convert script). Tested with bf16 on hybrid CUDA+CPU.
```bash
model=/mnt/raid/models/ubergarm/Hunyuan-A13B-Instruct-GGUF/Hunyuan-A13B-Instruct-BF16-00001-of-00004.gguf
./build/bin/llama-server \
--model "$model" \
--alias ubergarm/Hunyuan-A13B-Instruct-bf16 \
-fa \
-ctk q8_0 -ctv q8_0 \
-c 8192 \
--temp 0.6 \
--presence-penalty 0.7 \
--min-p 0.1 \
-ts 48,48 \
-ngl 16 \
--threads 24 \
--host 127.0.0.1 \
--port 8080
```
Would be great if anyone else could test e.g. @Downtown-Case as per #561 
I haven't yet made imatrix nor tried to quantize further.
Might be able to use one of the following if was converted recently enough:
* …

add hunyuan moe support for 561

---

include/llama.h
src/llama-vocab.cpp
src/llama.cpp
src/unicode.cpp
src/unicode.h

Ported kimi-k2 support from llama.cpp.
[Original patch](https://github.com/ggml-org/llama.cpp/pull/14654) by @gabriellarson

Added kimi-k2 support (ported from llama.cpp)

---

src/llama.cpp

Allows up to 2048 shards to be loaded on Windows builds, from the current default of 512. This change is specific to Windows, it instructs the Windows OS that the binary requires 2048 of max opened files. This is the equivalent to Linux's `ulimit -n`.

Bump Windows max open files from 512 to 2048

---

src/llama.cpp

Closes #464.
It seems there are models out there where the BOS token id is the same as the token ID of a comma (11 in the case of Qwen3 MoE models). This results in interpreting a comma during token generation as warm up run, which then results in using all experts, which makes the run time for the next token much longer, which then looks like a pause in the generation. The logic to use all experts during warm up was added in #198 to improve the user experience with very large MoE models.  
This PR fixes the issue by checking how many tokens have been evaluated in the given context and only creating a warm up graph if this is zero (in addition to the other conditions to detect a warm up run).

Fix pauses after a comma

---

ggml/src/ggml-cuda/mmq.cu
ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml-cuda/template-instances/mmq-instance-iq4_kss.cu
ggml/src/iqk/iqk_gemm_iqk_quants.cpp
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp

Not much is known about `IQ4_KSS`, and nobody seems to be using it. So, I decided to give it some attention.
Quick reminder (for more, see #89)
* `IQ4_KSS` uses exactly 4.0 bpw just like `IQ4_KT`
* Performance on CUDA is very similar to `IQ4_KT` (after this PR)
* PP CPU performance is similar to `IQ4_KT` (after this PR)
* TG CPU performance is quite a bit better than `IQ4_KT`
* PPL is only slightly worse than `IQ4_KT` 
This PR
* Adds CUDA quantized matrix multiplication kernel
* Adds repacking to `Q8_K_R8` for fast CPU GEMM
* Adds a small improvement in quantization accuracy

IQ4_KSS improvements

---

common/common.cpp

Simple port of https://github.com/ggml-org/llama.cpp/pull/15077.

Port cpu moe options from mainline

---

ggml/src/iqk/iqk_flash_attn.cpp

I was playing with the newly released 270M parameter Gemma3 models, and wasn't particularly impressed with the TG performance of `ik_llama.cpp` when running CPU-only (or put differently, I was hoping to get better CPU performance).
The Gemma3 models use SWA, and this is currently totally ignored in `ik_llama.cpp`. So, I decided to add a quick hack that reduces the cost of the self-attention calculation. CPU-only for now, flash attention required.
Tested on a Ryzen-7950X CPU with Gemma3-270M-it quantized with Q8_0, and the MXFP4 GPT-OSS-20B model. In both cases `Q8_0` is used for KV cache.
We see a factor of ~2X improvement at 32k tokens for Gemma3-270M, and ~10% improvement for GPT-OSS-20B at 16k tokens. In Gemma3 5 out of 6 layers are SWA with a window size of 512, while in GPT-OSS every …

Improve TG performance for SWA models (CPU)

---

examples/server/server.cpp

I added sending usage metrics that llama-swap and others use to display statistics, also corrected the formula for calculating timings and enabled `timings_per_token` by default (in theory it shouldn't have much of an impact on performance)

Added "usage" to server response

---

ggml/include/ggml.h
ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_mul_mat.h
src/llama.cpp

This PR is a follow up of #692 and uses the same technique to improve prompt processing performance for models utilizing SWA. As #682 it is implemented only on the CPU and requires FA.
Here some performance comparisons on a Ryzen-7950X CPU

Better CPU prompt processing performance for SWA models

---

ggml/src/ggml-cuda/fattn-wmma-f16.cuh
ggml/src/ggml-cuda/fattn.cu

There have been reports of `llama.cpp` being faster than `ik_llama.cpp` for the GLM-4.5 MoE models, see e.g. [here](https://github.com/ikawrakow/ik_llama.cpp/pull/689#issuecomment-3191092917) or [here](https://huggingface.co/ubergarm/GLM-4.5-Air-GGUF/discussions/2#68980a066bc7e6a3fcef131c), with the `llama.cpp` advantage increasing with context length, which points to a problem with the self-attention implementation in `ik_llama.cpp` for this specific model.
After wasting a lot of time scrutinizing the various kernels involved, I finally located the problem in [this  function](https://github.com/ikawrakow/ik_llama.cpp/blob/4bf5c8184b177ee5bbd77fc7fde34f57613c1f6b/ggml/src/ggml-cuda/fattn.cu#L72), where we have:
```c++
if (use_gqa_opt && gqa_ratio % 8 == 0) { …
```

Fix GLM-4.5 attention

---

examples/quantize-stats/quantize-stats.cpp

See #706 
The code that causes the MSVC build failure is just playing around with some statistics around quantization, so totally unused in practice. Instead of fighting with diverging compiler's opinions if `constexpr` can or cannot be used in lambdas, let's just disable this code.

Disable experimental code that causes issues with MSVC

---

ggml/src/ggml-cuda/iqk_mmvq.cu
ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml-cuda/template-instances/mmq-instance-iq4_kss.cu
ggml/src/ggml-cuda/vecdotq.cuh

There is [this PR](https://github.com/ggml-org/llama.cpp/pull/15451) in mainline `llama.cpp`. It uses the `__byte_perm` Nvidia intrinsics to more efficiently assemble a 32-bit integer when each byte requires a lookup in a table of 16 values. These are the newly added `MXFP4`, along with `IQ4_NL, IQ4_XS, IQ4_KS, IQ4_KS_R4, IQ4_KSS`. I had noticed the `__byte_perm` instruction when searching for other SIMD instrinsics in the CUDA manual and had made a mental note to investigate the use of this instruction for handling lookup tables, but mainline PR 15451 already did it, so I could just take it from there.
As `IQ4_K` (and `IQ4_K_R4`) use blocks of 16, so the first 2 and second 2 bytes require different lookup tables, the trick is not directly applicable to these quantization types.
Here a …

CUDA: faster prompt processing for 4-bit quants

---

ggml/include/ggml.h
ggml/src/ggml-common.h
ggml/src/ggml-quants.c
ggml/src/ggml.c
ggml/src/iqk/iqk_common.h
ggml/src/iqk/iqk_gemm_1bit.cpp
ggml/src/iqk/iqk_gemm_iqk_quants.cpp
ggml/src/iqk/iqk_gemm_iquants.cpp
ggml/src/iqk/iqk_gemm_kquants.cpp
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_quantize.cpp
ggml/src/iqk/iqk_quantize.h

This is an alternative to #610 
The expectation is that it will significantly improve CPU-only prompt processing speed on "true" `AVX512` CPUs that support the  `AVX512VNNI, AVX512VL, AVX512BW,` and `AVX512DQ` extensions (e.g., Zen5). These extensions are also supported by Zen4 cores, but these are not "true" `AVX512` CPUs as there 512-bit instructions are performed as two 256-bit instructions. The main benefit compared to #610 is that on such CPUs performance is about the same as on main, unlike #610, where we get a 10-15% performance penalty.IQ2_XXS
The PR adds a new quantization type, `Q8_K_R16`, which is only used for quantizing activation tensors. `IQ1_S, IQ1_M, IQ2_XXS, IQ2_XS, IQ2_S, IQ3_XXS, IQ3_S, IQ4_XS, Q2_K, Q3_K, IQ2_KS, IQ2_K, IQ3_KS, IQ3_K, IQ4_KSS, IQ4_KS, IQ4_K, IQ5_KS, …

AVX512+AVXVNNI GEMM implementation for quants using Q8_K for activations 

---

src/llama.cpp

When loading a DeepSeek model that does not have the attention `wkv_b` tensors included, `ik_llama.cpp` prints this scary warning 
```
==========================================================================
Detected incompatible DeepSeek model.
Will try to fix, but there are no guarantees
*** Your prompt processing speed will be crippled ***
Consider making your own ik_llama.cpp compatible model or
ask the model provider to make one for you,
==========================================================================
```
As the performance issues around missing `wkv_b` tensors were solved quite a while ago, there is no longer the need for this message. This PR removes it. It still logs
```
================= Adjusted mainline llama.cpp MLA tensors to ik_llama.cpp
```
so we know the …

Remove scary warning about incompatible model

---

common/common.cpp
common/common.h
examples/llama-bench/llama-bench.cpp
ggml/include/ggml.h
ggml/src/ggml-cuda.cu
ggml/src/ggml-cuda/mmq.cuh
ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
include/llama.h
src/llama.cpp

Similar to the fused `ffn_up/ffn_gate` op for MoE models, but applicable to regular FFN networks. As such, more relevant for dense models, where I observe a ~2.5% performance improvement for prompt processing, and ~0.6% for token generation for LlaMA-3-8B.
For MoE models there is no gain when there are no shared experts and no dense-lead layers, and a very minor performance gain (sub-1%) for models with shared experts (e.g., DeepSeek).
Only implemented for the CPU and CUDA back-ends for now. But given that `ik_llama.cpp` is predominantly used on these platforms, I decided to turn the option on by default. It can be turned off using `-no-fug` or `--no-fused-up-gate`.

Fused FFN_UP+FFN_GATE op

---

ggml/CMakeLists.txt

This is to avoid running into OOM situations, the latest being #749

Set default value of GGML_SCHED_MAX_COPIES to 1

---

ggml/src/ggml.c
ggml/src/iqk/iqk_flash_attn.cpp
ggml/src/iqk/iqk_mul_mat.h

This is an alternative, and much simpler implementation compared to #702,  of the CPU FA optimization for SWA models. 
It achieves similar prompt processing speedup as #702.  For instance, at 32k tokens running on a Ryzen-7950X CPU, PP is about 1.6X faster for `GPT-OSS-20B-MXFP4`, and 2.1X faster for `Gemma3-12B-Q4_0` compared to the main branch.
|  1024 |    256 |      0 |    1.980 |   517.07 |   11.838 |    21.62 |
|  1024 |    256 |   1024 |    2.131 |   480.51 |   12.088 |    21.18 |
|  1024 |    256 |   2048 |    2.289 |   447.43 |   12.292 |    20.83 |
|  1024 |    256 |   3072 |    2.471 |   414.40 |   12.394 |    20.66 |
|  1024 |    256 | …

Better CPU SWA

---

ggml/src/ggml-cuda.cu
src/llama.cpp

This fixed the crash when doing context shift for quantized kv cache. Before this PR, I can only use fp16 for kv cache . Tested with both q8_0 and q4_0 and don't see crash.
https://github.com/ggml-org/llama.cpp/pull/9571
It will fail on unsupported backends or quant types.

llama: Enable K-shift for quantized KV cache for cuda

---

ggml/src/ggml.c

Otherwise hybrid inference with quants that have per row scales leads to an assert for MoE models.

Fix ggml_is_contiguously_allocated

---

ggml/src/ggml.c
ggml/src/iqk/iqk_mul_mat.cpp
ggml/src/iqk/iqk_mul_mat.h

CPU implementation of fused top-k + softmax. See also #789, which did the same for the CUDA back-end.
Leads to 2-3% PP and TG improvement for most MoE models.

cpu: fused softmax+topk

---

ggml/src/ggml-cuda.cu
ggml/src/ggml.c
src/llama.cpp

This PR adds the ability to fuse quantized matrix multiplication that operate on the same activations $A$. A typical example where fusing can be done for most models are the $Q \cdot A$, $K \cdot A$ and $V \cdot A$ products. The implementation does not go as far as fusing these into a single kernel, but it does save the quantization of $A$ into the required type, along with the thread synchronization between such matrix multiplications.
The performance gain is surprisingly small, typically being $\le 1$%. Nevertheless, adding this micro-optimization.

Fused matrix multiplications (CUDA and CPU)

---

src/llama.cpp

Fixes: https://github.com/ikawrakow/ik_llama.cpp/issues/812
By marking a few tensors as optional. GLM 4.6 loads and inferences for me, if you wish to test: https://huggingface.co/Downtown-Case/GLM-4.6-128GB-RAM-IK-GGUF
Plucked from: https://github.com/ggml-org/llama.cpp/pull/16359
***
Random aside, but this might be a good opportunity to make sure the MTP (multi-token prediction) tensors are never loaded into RAM, since they are not used anyway? Their size is on the order of ~2GB quantized, I think, which is signficant when squeezing in a >3bpw quant.

Add GLM 4.6 support
