ikawrakow/ik_llama.cpp

ggml/src/ggml.c
It seemed Gemma-2 performance is lower than expected for its size. Looking at the architecture, I noticed that `tanh` is used in each layer, and then at the end for soft-caping the final output. `ggml` had `tanh` set to be computed with a single thread. Combined with `tanh(x)` being a pretty expensive operation, this resulted in a significant fraction of the time being spent in the `tanh` operation.
After multi-threading `ggml_vec_soft_max_f32` and simd-ifying the `tanh` computation, I observe a 33% gain in prompt processing speed for Gemma-2-9b (!!!) TG is of course memory bound, but despite this, we still get a ~2% boost at 4 threads (which gives max TG performance on my Ryzen-7950X).
Simd-ifying:
We have
```
tanh(x) = (exp(2*x) - 1)/(exp(2*x) + 1)
```
so we can just use Justine …
=> Simdify and multi-thread tanh

Makefile, ggml/src/iqk/iqk_quantize.cpp
I always use cmake, so had forgotten to pay attention to the Makefile.
=> Fix Makefile

examples/quantize-stats/quantize-stats.cpp
This allows for a better comparison between different models or different tensors of the same model where the magnitude of the model weights may differ.
=> quantize_stats: print rmse and max error as fraction of <x>

ggml/src/ggml-quants.c, ggml/src/iqk/iqk_quantize.cpp, ggml/src/iqk/iqk_quantize.h
It has been there for a while, but forgot to add here.
=> AVX2 quantization for Q8_K

Makefile, ggml/src/iqk/iqk_quantize.cpp
=> Fix build when iqk_mul_mat is disabled

ggml/src/iqk/iqk_mul_mat.cpp
We get `PP-512 = 545` t/s for the 4B TriLM model compared to `PP-512 = 498` t/s on the main branch (on a Ryzen-5975WX). TG is not affected.
It is possible to increase `PP-512` performance to 600 t/s by representing `IQ2_TN` as a row scale + `IQ1_BN` packed quants, and reusing the `IQ2_BN` implementation, see the [iq2_tn_as_iq2_bn branch](https://github.com/ikawrakow/ik_llama.cpp/tree/ik/iq2_tn_as_iq2_bn). The issue with the `iq2_tn_as_iq2_bn` implementation is that TG performance on the Ryzen-5975WX saturates at about 38 t/s, while here we have 50.5 t/s. So, preferring this change for now, perhaps I can sort out where the TG bottleneck is in `iq2_tn_as_iq2_bn` later.
=> iq2_tn: slightly better performance on AVX2

ggml/src/iqk/iqk_mul_mat.cpp
This PR adds the ability to use Q4_0, Q4_1 and Q8_0 for the kv-cache.
=> AVX2 Flash Attention 2

ggml/src/ggml-quants.c
Speeds up CPU flash attention using `IQ4_NL`.
**Of note**: I noticed `Q8_0` cannot be used for V-cache when head size is not divisible by 128. This is because of
* My change to `quantize_row_q8_0` to store data in groups of 4 blocks. This speeds up legacy quants and `IQ4_NL` matrix multiplications
* The fact that when `V` is stored into the cache, it is treated as being a contiguous 2D tensor. As a result, the groups-of-4 storage strategy is applied. But when used in FA, the `V` tensor is viewed as a non-contiguous 3D tensor with second and third dimension permuted, so for heads that are not a multiple of 128, data in groups-of-4 ends up in different heads. 
To fix this, one would need to
* Revert the change to `quantize_row_q8_0`
* Introduce a new quantization type for usage as the …
=> iq4_nl: faster quantization

examples/quantize-stats/quantize-stats.cpp, src/llama.cpp
In the quantization literature they always ignore the token embedding and output tensors (they leave them as `f16`). But when `llama.cpp` loads a model, it prints a bits-per-weight (bpw) value that is basically `total file size on disk / total number of parameters`. As this includes the output tensor, which is almost always quantized with more bpw, this makes the i- and k-quants appear not competitive.
So, this PR adds an additional print out that tells us the model size excluding `token_embd.weight` and `output.weight`, and the corresponding bpw. Here is an example from LLaMA-3.1-8B-Instruct quantized with `IQ2_XS`:
```
...
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = IQ2_XS - 2.3125 bpw
llm_load_print_meta: model params     = 8.030 B …
```
=> Better model info

ggml/src/ggml-metal.metal
Haha, I keep forgetting that the Metal compiler often needs a hand to produce fast code.
In this particular instance, we gain almost 8.5% token generation (TG) speedup for `IQ4_KS`:
TG-128(LLaMA-3.1-8B) goes to 52.5 t/s up from 48.4 t/s on my M2-Max 30-core GPU.
The actual computation did not change in any way, we just helped the compiler fetch data ore effectively.
=> iq4_ks: faster dot product on Metal

ggml/src/iqk/iqk_mul_mat.cpp
Ref #88 
@Nexesenex @saood06
Does this work?
=> Attempt to blindly fix Windows build failure

ggml/src/ggml-metal.metal
This time just the dequantize function. 
For Bitnet-1.58b-3B on 30-core M2-Max GPU 
* `IQ1_BN` goes from 702 t/s to 716 t/s
* `IQ2_BN` goes from 714 t/s to 743 t/s
=> Another Bitnet performance improvement on Metal

ggml/src/ggml-cuda/iqk_mmvq.cu
`IQ1_BN` TG-128 on RTX-4080 goes to 340 t/s up from 318 t/s.
On the front page the performance listed for `IQ1_BN` on CUDA is 301 t/s, so a pretty nice improvement since then.
=> Bitnet CUDA improvements

src/llama.cpp
This gives us a ~1% speedup for MoE models on CUDA and Metal.
=> Use fused mul - unary op also for MoE models

ggml/src/iqk/iqk_mul_mat.cpp
=> Slightly faster Q4_K_R4 and IQ4_XS_R4 on Zen4

ggml/src/iqk/iqk_mul_mat.cpp
Performance is better. Packing quants into 512-bit registers is costly and when we have just 1 column to multiply, using the `AVX512` version becomes slower. I had already done this for most (all?) other quants, but somehow missed `Q4_0`.
=> q4_0_r4: Use AVX2 version for matrix x vector

include/llama.h, src/llama.cpp
Basically sync with `llama.cpp`
=> Update chat templates

ggml/src/iqk/iqk_mul_mat.cpp
=> Fix iqk_mul_mat on AVX512 systems that are missing BF16 support

ggml/src/iqk/iqk_mul_mat.cpp
=> Fix compilation error with IQK_FA_ALL_QUANTS enabled

ggml/src/ggml.c
Trying to measure it on each `ggml_barrier` invocation is too imprecise as the best time resolution we have in `ggml` is 1 us. Hence, measure the total graph execution time and and the sum of the node execution times. The difference is then the cost of thread synchronization via `ggml_barrier`.
Using this on TG runs with DeepSeek-Lite I'm finding that `ggml_barrier` costs about 7% of the graph evaluation time when running on the CPU.
=> A better way to measure the cost of ggml_barrier

ggml/src/ggml-cuda.cu, ggml/src/ggml-cuda/cpy.cu
Performance is slightly lower than `f16` KV cache but not too bad.
=> MLA-2: Allow usage of q8_0 for KV cache  on CUDA

ggml/src/CMakeLists.txt
=> Native build ooption for CUDA when GGML_NATIVE is set

src/llama.cpp
Apparently not all use cases are covered when using interleaved quants, see #296.
Hopefully this PR handles all scenarios where one may arrive at using an interleaved quantization type where this is not possible.
=> Additional guards for interleaved quants

ggml/src/ggml-alloc.c, ggml/src/iqk/iqk_quantize.cpp
I meant to also do `ARM_NEON` before merging #292 and then I forgot. This PR fixes the build failure.
=> Fix ARM_NEON build failure due to q8_2

ggml/src/iqk/iqk_mul_mat.cpp
=> Fix GCC compilation errors on ARM

ggml/src/ggml-cuda.cu
Thanks to @JohannesGaessler for noticing.
=> We need to synchronize before using device to host async memcpy

examples/imatrix/imatrix.cpp
@ubergarm
Here is how one can collect statistics about the activations change caused by a layer using cosine similarity.
=> imatrix: collect layer influence statistics

src/llama.cpp
Closes #335 
I had missed the SWA part. As SWA only has a real impact past 8k tokens, and as the impact of not using SWA is relatively small for the next 8k tokens, the model appeared coherent up to 16k tokens.
It now produces the following summary of the first 23.5k tokens of the Wikipedia article on Artificial Intelligence:
```
Here is a brief summary of the article on Artificial Intelligence (AI):
**What is AI?**
Artificial intelligence refers to the capability of computer systems to perform tasks typically associated with human intelligence, such as learning, reasoning, problem-solving, perception, and decision-making.
**Applications of AI**
High-profile applications of AI include advanced web search engines, recommendation systems, virtual assistants, autonomous vehicles, generative …
```
=> Fix LLaMA-4 attention

ggml/src/iqk/iqk_mul_mat.cpp
=> Fix FA on ARM CPUs

ggml/src/iqk/iqk_mul_mat.cpp
=> Fix IQK_FA_ALL_QUANTS on AVX2

ggml/src/iqk/iqk_quantize.cpp
=> Trying to fix iq1_s_r4/iq1_m_r4 quantization failure

ggml/src/iqk/iqk_quantize.cpp
Fix `IQ1_M_R4` quantization failure.
Closes #367
=> Another attempt to fix #367

ggml/src/iqk/iqk_mul_mat.cpp
I have focusing on FA, MLA, FlashMLA lately, and at some point I have broken the standard self attention CPU implementation. This PR fixes it and closes #420.
=> Fix standard attention on the CPU

ggml/include/ggml-backend.h, ggml/src/ggml-backend.c, ggml/src/ggml-cuda.cu, ggml/src/ggml-cuda/fattn-new-mma.cu
Do these fix the mysterious illegal memory access crashes?
I doubt it, but who knows.
Ref #389, #425
=> Bug fixes from mainline

examples/quantize-stats/quantize-stats.cpp, ggml/src/iqk/iqk_gemm_ktquants.cpp
MSVC does not like `^` with SIMD vectors.
Closes #447
=> Fix MSVC compilation

README.md
@ikawrakow 
Making this draft PR to get your feedback on this format before I add all the new ones (and add in all the missing links). 
Do you see any way to condense the sections that are currently one PR per line? (Maybe subsections of Performance improvements?)
And if any of them can be removed as they are no longer relevant (especially if MLA-2 is deprecated)
=> Update News section of readme

ggml/src/iqk/iqk_gemm_iqk_quants.cpp, ggml/src/iqk/iqk_gemm_iquants.cpp, ggml/src/iqk/iqk_gemm_kquants.cpp, ggml/src/iqk/iqk_gemm_ktquants.cpp, ggml/src/iqk/iqk_gemm_legacy_quants.cpp
I did not pay attention to the `ARM_NEON` build with the recent PP performance improvement PRs, so now the main branch does not even build. This PR fixes that (but nothing will be working).
=> Fix NEON build

src/llama.cpp
Last PR just disabled them, here we disable them only if building with Vulkan support.
This is temporary until the fused ops are implemented in the Vulkan backend.
=> Conditionally disable fused ops when building with Vulkan enabled

ggml/src/ggml-vulkan.cpp, ggml/src/vulkan-shaders/fused_rms_norm.comp, ggml/src/vulkan-shaders/vulkan-shaders-gen.cpp, src/llama.cpp
I see zero performance benefit, but at least we don't need to cpecial-case Vulkan when creating the graph.
=> Vulkan: fused rms norm

ggml/src/ggml-cuda.cu
In #589 I added an optimization of the fused ffn_up/gate op to not repeat the quantization of the activations when `ffn_up` and `ffn_gate` are quantized with the same type. But the check to use the direct route did not consider the possibility that some quantization types do not have MMQ implementation (e.g., `IQ1_M`), which then results in an assert.
This PR adds the missing check, which should fix #596
=> Check if MMQ should be used before using it

src/llama.cpp
To retain compatibility with : https://github.com/ikawrakow/ik_llama.cpp/pull/91 We need "else if" and not "if", otherwise the MOE and 70b condition takes precedence over the specified quant in the CLI.
I can also expand this legacy custom quant to the IQ1 and IQ2 types quant strategies tree, and add the shexp tensor to it, if that's all right.
=> Fix attn_v conditionality when quantizing.

ggml/src/iqk/iqk_gemm_1bit.cpp, ggml/src/iqk/iqk_mul_mat.cpp
Did not make it into #630, so adding t here.
=> IQ1_M GEMM for ARM_NEON

examples/server/function_calls.hpp
I cannot actually run DeepSeek-R1, and I have no test case, so just a shot in the dark.
=> Does this fix #690?

ggml/src/iqk/iqk_quantize.cpp
This PR adds more sanity checks on model weights and imatrix values for trellis quantization (`IQ1_KT, IQ2_KT, IQ3_KT, IQ4_KT`).
@ubergarm Does this fix the problem reported in #650 ?
=> Sanitize importances for KT quantization

src/llama.cpp
Fixes #793 
When quantizing with `--allow-requantize` and the tensor being converted is quantized, the implementation inherited from mainline makes the by now legendary assumption of contiguous quantized blocks when converting the quantized data to `f32`. This fails for quantization types that use per tensor row scales (trellis quants, `IQX_KS`, `IQX_KSS`). This PR fixes the issue.
=> Fix dequantization when requantizing
